// Code generated by protoc-gen-go. DO NOT EDIT.
// source: naturaeproto/Naturae.proto

package naturaeproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CreateAccountRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=appKey,proto3" json:"appKey,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	FirstName            string   `protobuf:"bytes,4,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,5,opt,name=lastName,proto3" json:"lastName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{2}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *CreateAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateAccountRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateAccountRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type CreateAccountReply struct {
	Status               *Status  `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountReply) Reset()         { *m = CreateAccountReply{} }
func (m *CreateAccountReply) String() string { return proto.CompactTextString(m) }
func (*CreateAccountReply) ProtoMessage()    {}
func (*CreateAccountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{3}
}

func (m *CreateAccountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountReply.Unmarshal(m, b)
}
func (m *CreateAccountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountReply.Marshal(b, m, deterministic)
}
func (m *CreateAccountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountReply.Merge(m, src)
}
func (m *CreateAccountReply) XXX_Size() int {
	return xxx_messageInfo_CreateAccountReply.Size(m)
}
func (m *CreateAccountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountReply proto.InternalMessageInfo

func (m *CreateAccountReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type LoginRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=appKey,proto3" json:"appKey,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{4}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginReply struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Status               *Status  `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{5}
}

func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (m *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(m, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

func (m *LoginReply) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *LoginReply) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *LoginReply) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *LoginReply) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *LoginReply) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type AccountAuthenRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=appKey,proto3" json:"appKey,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	AuthenCode           string   `protobuf:"bytes,5,opt,name=authenCode,proto3" json:"authenCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountAuthenRequest) Reset()         { *m = AccountAuthenRequest{} }
func (m *AccountAuthenRequest) String() string { return proto.CompactTextString(m) }
func (*AccountAuthenRequest) ProtoMessage()    {}
func (*AccountAuthenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{6}
}

func (m *AccountAuthenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountAuthenRequest.Unmarshal(m, b)
}
func (m *AccountAuthenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountAuthenRequest.Marshal(b, m, deterministic)
}
func (m *AccountAuthenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountAuthenRequest.Merge(m, src)
}
func (m *AccountAuthenRequest) XXX_Size() int {
	return xxx_messageInfo_AccountAuthenRequest.Size(m)
}
func (m *AccountAuthenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountAuthenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountAuthenRequest proto.InternalMessageInfo

func (m *AccountAuthenRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *AccountAuthenRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AccountAuthenRequest) GetAuthenCode() string {
	if m != nil {
		return m.AuthenCode
	}
	return ""
}

type AccountAuthenReply struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Status               *Status  `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountAuthenReply) Reset()         { *m = AccountAuthenReply{} }
func (m *AccountAuthenReply) String() string { return proto.CompactTextString(m) }
func (*AccountAuthenReply) ProtoMessage()    {}
func (*AccountAuthenReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{7}
}

func (m *AccountAuthenReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountAuthenReply.Unmarshal(m, b)
}
func (m *AccountAuthenReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountAuthenReply.Marshal(b, m, deterministic)
}
func (m *AccountAuthenReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountAuthenReply.Merge(m, src)
}
func (m *AccountAuthenReply) XXX_Size() int {
	return xxx_messageInfo_AccountAuthenReply.Size(m)
}
func (m *AccountAuthenReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountAuthenReply.DiscardUnknown(m)
}

var xxx_messageInfo_AccountAuthenReply proto.InternalMessageInfo

func (m *AccountAuthenReply) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AccountAuthenReply) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *AccountAuthenReply) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *AccountAuthenReply) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *AccountAuthenReply) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AccountAuthenReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type CreatePostRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=appKey,proto3" json:"appKey,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Species              string   `protobuf:"bytes,4,opt,name=species,proto3" json:"species,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Lat                  float32  `protobuf:"fixed32,6,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float32  `protobuf:"fixed32,7,opt,name=lng,proto3" json:"lng,omitempty"`
	EncodedImage         string   `protobuf:"bytes,8,opt,name=encodedImage,proto3" json:"encodedImage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{8}
}

func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(m, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *CreatePostRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *CreatePostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreatePostRequest) GetSpecies() string {
	if m != nil {
		return m.Species
	}
	return ""
}

func (m *CreatePostRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreatePostRequest) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *CreatePostRequest) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *CreatePostRequest) GetEncodedImage() string {
	if m != nil {
		return m.EncodedImage
	}
	return ""
}

type CreatePostReply struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostReply) Reset()         { *m = CreatePostReply{} }
func (m *CreatePostReply) String() string { return proto.CompactTextString(m) }
func (*CreatePostReply) ProtoMessage()    {}
func (*CreatePostReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{9}
}

func (m *CreatePostReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostReply.Unmarshal(m, b)
}
func (m *CreatePostReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostReply.Marshal(b, m, deterministic)
}
func (m *CreatePostReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostReply.Merge(m, src)
}
func (m *CreatePostReply) XXX_Size() int {
	return xxx_messageInfo_CreatePostReply.Size(m)
}
func (m *CreatePostReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostReply proto.InternalMessageInfo

func (m *CreatePostReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetPostRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=appKey,proto3" json:"appKey,omitempty"`
	Lat                  float32  `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float32  `protobuf:"fixed32,3,opt,name=lng,proto3" json:"lng,omitempty"`
	Radius               int32    `protobuf:"varint,4,opt,name=radius,proto3" json:"radius,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostRequest) Reset()         { *m = GetPostRequest{} }
func (m *GetPostRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostRequest) ProtoMessage()    {}
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{10}
}

func (m *GetPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostRequest.Unmarshal(m, b)
}
func (m *GetPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostRequest.Marshal(b, m, deterministic)
}
func (m *GetPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostRequest.Merge(m, src)
}
func (m *GetPostRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostRequest.Size(m)
}
func (m *GetPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostRequest proto.InternalMessageInfo

func (m *GetPostRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *GetPostRequest) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *GetPostRequest) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *GetPostRequest) GetRadius() int32 {
	if m != nil {
		return m.Radius
	}
	return 0
}

type GetPostReply struct {
	Status               *Status               `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Reply                []*GetPostReplyStruct `protobuf:"bytes,2,rep,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetPostReply) Reset()         { *m = GetPostReply{} }
func (m *GetPostReply) String() string { return proto.CompactTextString(m) }
func (*GetPostReply) ProtoMessage()    {}
func (*GetPostReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{11}
}

func (m *GetPostReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostReply.Unmarshal(m, b)
}
func (m *GetPostReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostReply.Marshal(b, m, deterministic)
}
func (m *GetPostReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostReply.Merge(m, src)
}
func (m *GetPostReply) XXX_Size() int {
	return xxx_messageInfo_GetPostReply.Size(m)
}
func (m *GetPostReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostReply proto.InternalMessageInfo

func (m *GetPostReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetPostReply) GetReply() []*GetPostReplyStruct {
	if m != nil {
		return m.Reply
	}
	return nil
}

type GetPostReplyStruct struct {
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Species              string   `protobuf:"bytes,4,opt,name=species,proto3" json:"species,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Lat                  float32  `protobuf:"fixed32,6,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float32  `protobuf:"fixed32,7,opt,name=lng,proto3" json:"lng,omitempty"`
	EncodedImage         string   `protobuf:"bytes,8,opt,name=encodedImage,proto3" json:"encodedImage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostReplyStruct) Reset()         { *m = GetPostReplyStruct{} }
func (m *GetPostReplyStruct) String() string { return proto.CompactTextString(m) }
func (*GetPostReplyStruct) ProtoMessage()    {}
func (*GetPostReplyStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{12}
}

func (m *GetPostReplyStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostReplyStruct.Unmarshal(m, b)
}
func (m *GetPostReplyStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostReplyStruct.Marshal(b, m, deterministic)
}
func (m *GetPostReplyStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostReplyStruct.Merge(m, src)
}
func (m *GetPostReplyStruct) XXX_Size() int {
	return xxx_messageInfo_GetPostReplyStruct.Size(m)
}
func (m *GetPostReplyStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostReplyStruct.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostReplyStruct proto.InternalMessageInfo

func (m *GetPostReplyStruct) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetPostReplyStruct) GetSpecies() string {
	if m != nil {
		return m.Species
	}
	return ""
}

func (m *GetPostReplyStruct) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetPostReplyStruct) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *GetPostReplyStruct) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *GetPostReplyStruct) GetEncodedImage() string {
	if m != nil {
		return m.EncodedImage
	}
	return ""
}

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{13}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetAccessTokenRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=appKey,proto3" json:"appKey,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccessTokenRequest) Reset()         { *m = GetAccessTokenRequest{} }
func (m *GetAccessTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenRequest) ProtoMessage()    {}
func (*GetAccessTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{14}
}

func (m *GetAccessTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenRequest.Unmarshal(m, b)
}
func (m *GetAccessTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetAccessTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenRequest.Merge(m, src)
}
func (m *GetAccessTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenRequest.Size(m)
}
func (m *GetAccessTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenRequest proto.InternalMessageInfo

func (m *GetAccessTokenRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *GetAccessTokenRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type GetAccessTokenReply struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccessTokenReply) Reset()         { *m = GetAccessTokenReply{} }
func (m *GetAccessTokenReply) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenReply) ProtoMessage()    {}
func (*GetAccessTokenReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{15}
}

func (m *GetAccessTokenReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenReply.Unmarshal(m, b)
}
func (m *GetAccessTokenReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenReply.Marshal(b, m, deterministic)
}
func (m *GetAccessTokenReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenReply.Merge(m, src)
}
func (m *GetAccessTokenReply) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenReply.Size(m)
}
func (m *GetAccessTokenReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenReply proto.InternalMessageInfo

func (m *GetAccessTokenReply) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetAccessTokenReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type ForgetPasswordRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=AppKey,proto3" json:"AppKey,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetPasswordRequest) Reset()         { *m = ForgetPasswordRequest{} }
func (m *ForgetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgetPasswordRequest) ProtoMessage()    {}
func (*ForgetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{16}
}

func (m *ForgetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetPasswordRequest.Unmarshal(m, b)
}
func (m *ForgetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ForgetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetPasswordRequest.Merge(m, src)
}
func (m *ForgetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgetPasswordRequest.Size(m)
}
func (m *ForgetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetPasswordRequest proto.InternalMessageInfo

func (m *ForgetPasswordRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *ForgetPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ForgetPasswordReply struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetPasswordReply) Reset()         { *m = ForgetPasswordReply{} }
func (m *ForgetPasswordReply) String() string { return proto.CompactTextString(m) }
func (*ForgetPasswordReply) ProtoMessage()    {}
func (*ForgetPasswordReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{17}
}

func (m *ForgetPasswordReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetPasswordReply.Unmarshal(m, b)
}
func (m *ForgetPasswordReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetPasswordReply.Marshal(b, m, deterministic)
}
func (m *ForgetPasswordReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetPasswordReply.Merge(m, src)
}
func (m *ForgetPasswordReply) XXX_Size() int {
	return xxx_messageInfo_ForgetPasswordReply.Size(m)
}
func (m *ForgetPasswordReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetPasswordReply.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetPasswordReply proto.InternalMessageInfo

func (m *ForgetPasswordReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type ForgetPasswordVerifyCodeRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=AppKey,proto3" json:"AppKey,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	VerificationCode     string   `protobuf:"bytes,3,opt,name=VerificationCode,proto3" json:"VerificationCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetPasswordVerifyCodeRequest) Reset()         { *m = ForgetPasswordVerifyCodeRequest{} }
func (m *ForgetPasswordVerifyCodeRequest) String() string { return proto.CompactTextString(m) }
func (*ForgetPasswordVerifyCodeRequest) ProtoMessage()    {}
func (*ForgetPasswordVerifyCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{18}
}

func (m *ForgetPasswordVerifyCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetPasswordVerifyCodeRequest.Unmarshal(m, b)
}
func (m *ForgetPasswordVerifyCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetPasswordVerifyCodeRequest.Marshal(b, m, deterministic)
}
func (m *ForgetPasswordVerifyCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetPasswordVerifyCodeRequest.Merge(m, src)
}
func (m *ForgetPasswordVerifyCodeRequest) XXX_Size() int {
	return xxx_messageInfo_ForgetPasswordVerifyCodeRequest.Size(m)
}
func (m *ForgetPasswordVerifyCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetPasswordVerifyCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetPasswordVerifyCodeRequest proto.InternalMessageInfo

func (m *ForgetPasswordVerifyCodeRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *ForgetPasswordVerifyCodeRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ForgetPasswordVerifyCodeRequest) GetVerificationCode() string {
	if m != nil {
		return m.VerificationCode
	}
	return ""
}

type ForgetPasswordVerifyCodeReply struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetPasswordVerifyCodeReply) Reset()         { *m = ForgetPasswordVerifyCodeReply{} }
func (m *ForgetPasswordVerifyCodeReply) String() string { return proto.CompactTextString(m) }
func (*ForgetPasswordVerifyCodeReply) ProtoMessage()    {}
func (*ForgetPasswordVerifyCodeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{19}
}

func (m *ForgetPasswordVerifyCodeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetPasswordVerifyCodeReply.Unmarshal(m, b)
}
func (m *ForgetPasswordVerifyCodeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetPasswordVerifyCodeReply.Marshal(b, m, deterministic)
}
func (m *ForgetPasswordVerifyCodeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetPasswordVerifyCodeReply.Merge(m, src)
}
func (m *ForgetPasswordVerifyCodeReply) XXX_Size() int {
	return xxx_messageInfo_ForgetPasswordVerifyCodeReply.Size(m)
}
func (m *ForgetPasswordVerifyCodeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetPasswordVerifyCodeReply.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetPasswordVerifyCodeReply proto.InternalMessageInfo

func (m *ForgetPasswordVerifyCodeReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type ForgetPasswordNewPasswordRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=AppKey,proto3" json:"AppKey,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetPasswordNewPasswordRequest) Reset()         { *m = ForgetPasswordNewPasswordRequest{} }
func (m *ForgetPasswordNewPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgetPasswordNewPasswordRequest) ProtoMessage()    {}
func (*ForgetPasswordNewPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{20}
}

func (m *ForgetPasswordNewPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetPasswordNewPasswordRequest.Unmarshal(m, b)
}
func (m *ForgetPasswordNewPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetPasswordNewPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ForgetPasswordNewPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetPasswordNewPasswordRequest.Merge(m, src)
}
func (m *ForgetPasswordNewPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgetPasswordNewPasswordRequest.Size(m)
}
func (m *ForgetPasswordNewPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetPasswordNewPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetPasswordNewPasswordRequest proto.InternalMessageInfo

func (m *ForgetPasswordNewPasswordRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *ForgetPasswordNewPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ForgetPasswordNewPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ForgetPasswordNewPasswordReply struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetPasswordNewPasswordReply) Reset()         { *m = ForgetPasswordNewPasswordReply{} }
func (m *ForgetPasswordNewPasswordReply) String() string { return proto.CompactTextString(m) }
func (*ForgetPasswordNewPasswordReply) ProtoMessage()    {}
func (*ForgetPasswordNewPasswordReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{21}
}

func (m *ForgetPasswordNewPasswordReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetPasswordNewPasswordReply.Unmarshal(m, b)
}
func (m *ForgetPasswordNewPasswordReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetPasswordNewPasswordReply.Marshal(b, m, deterministic)
}
func (m *ForgetPasswordNewPasswordReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetPasswordNewPasswordReply.Merge(m, src)
}
func (m *ForgetPasswordNewPasswordReply) XXX_Size() int {
	return xxx_messageInfo_ForgetPasswordNewPasswordReply.Size(m)
}
func (m *ForgetPasswordNewPasswordReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetPasswordNewPasswordReply.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetPasswordNewPasswordReply proto.InternalMessageInfo

func (m *ForgetPasswordNewPasswordReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type ChangePasswordRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=AppKey,proto3" json:"AppKey,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	CurrentPassword      string   `protobuf:"bytes,3,opt,name=CurrentPassword,proto3" json:"CurrentPassword,omitempty"`
	NewPassword          string   `protobuf:"bytes,4,opt,name=NewPassword,proto3" json:"NewPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{22}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *ChangePasswordRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *ChangePasswordRequest) GetCurrentPassword() string {
	if m != nil {
		return m.CurrentPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ChangePasswordReply struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordReply) Reset()         { *m = ChangePasswordReply{} }
func (m *ChangePasswordReply) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordReply) ProtoMessage()    {}
func (*ChangePasswordReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{23}
}

func (m *ChangePasswordReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordReply.Unmarshal(m, b)
}
func (m *ChangePasswordReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordReply.Marshal(b, m, deterministic)
}
func (m *ChangePasswordReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordReply.Merge(m, src)
}
func (m *ChangePasswordReply) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordReply.Size(m)
}
func (m *ChangePasswordReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordReply.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordReply proto.InternalMessageInfo

func (m *ChangePasswordReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "naturaeproto.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "naturaeproto.HelloReply")
	proto.RegisterType((*CreateAccountRequest)(nil), "naturaeproto.CreateAccountRequest")
	proto.RegisterType((*CreateAccountReply)(nil), "naturaeproto.CreateAccountReply")
	proto.RegisterType((*LoginRequest)(nil), "naturaeproto.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "naturaeproto.LoginReply")
	proto.RegisterType((*AccountAuthenRequest)(nil), "naturaeproto.AccountAuthenRequest")
	proto.RegisterType((*AccountAuthenReply)(nil), "naturaeproto.AccountAuthenReply")
	proto.RegisterType((*CreatePostRequest)(nil), "naturaeproto.CreatePostRequest")
	proto.RegisterType((*CreatePostReply)(nil), "naturaeproto.CreatePostReply")
	proto.RegisterType((*GetPostRequest)(nil), "naturaeproto.GetPostRequest")
	proto.RegisterType((*GetPostReply)(nil), "naturaeproto.GetPostReply")
	proto.RegisterType((*GetPostReplyStruct)(nil), "naturaeproto.GetPostReplyStruct")
	proto.RegisterType((*Status)(nil), "naturaeproto.Status")
	proto.RegisterType((*GetAccessTokenRequest)(nil), "naturaeproto.GetAccessTokenRequest")
	proto.RegisterType((*GetAccessTokenReply)(nil), "naturaeproto.GetAccessTokenReply")
	proto.RegisterType((*ForgetPasswordRequest)(nil), "naturaeproto.ForgetPasswordRequest")
	proto.RegisterType((*ForgetPasswordReply)(nil), "naturaeproto.ForgetPasswordReply")
	proto.RegisterType((*ForgetPasswordVerifyCodeRequest)(nil), "naturaeproto.ForgetPasswordVerifyCodeRequest")
	proto.RegisterType((*ForgetPasswordVerifyCodeReply)(nil), "naturaeproto.ForgetPasswordVerifyCodeReply")
	proto.RegisterType((*ForgetPasswordNewPasswordRequest)(nil), "naturaeproto.ForgetPasswordNewPasswordRequest")
	proto.RegisterType((*ForgetPasswordNewPasswordReply)(nil), "naturaeproto.ForgetPasswordNewPasswordReply")
	proto.RegisterType((*ChangePasswordRequest)(nil), "naturaeproto.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordReply)(nil), "naturaeproto.ChangePasswordReply")
}

func init() { proto.RegisterFile("naturaeproto/Naturae.proto", fileDescriptor_bdd2b78300d408eb) }

var fileDescriptor_bdd2b78300d408eb = []byte{
	// 948 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x57, 0xdf, 0x6e, 0x1b, 0xc5,
	0x17, 0xf6, 0xda, 0xb1, 0xe3, 0x9e, 0xf8, 0x97, 0xb6, 0x53, 0xa7, 0xf2, 0x6f, 0xe9, 0x1f, 0x33,
	0x48, 0x28, 0x40, 0x31, 0x52, 0x90, 0x7a, 0x5b, 0x39, 0x56, 0x1b, 0x10, 0xd4, 0x8a, 0x6c, 0x04,
	0xa8, 0x12, 0x42, 0xc3, 0xfa, 0xc4, 0x59, 0xb1, 0xde, 0x35, 0x3b, 0x63, 0xd2, 0x08, 0xf1, 0x22,
	0x48, 0xbc, 0x02, 0xcf, 0xc2, 0x25, 0x6f, 0xc0, 0x23, 0x70, 0x8b, 0xe6, 0xcf, 0xc6, 0xb3, 0xb3,
	0x6b, 0x77, 0x2d, 0x71, 0x81, 0xb8, 0xf2, 0x9e, 0x33, 0x67, 0xce, 0x7c, 0xdf, 0x37, 0x33, 0x67,
	0x8e, 0xc1, 0x8f, 0x99, 0x58, 0xa5, 0x0c, 0x97, 0x69, 0x22, 0x92, 0x8f, 0xc6, 0xda, 0x18, 0x28,
	0x8b, 0x74, 0xec, 0x31, 0x4a, 0xa1, 0xf3, 0x09, 0x46, 0x51, 0x32, 0xc1, 0x1f, 0x56, 0xc8, 0x05,
	0x21, 0xb0, 0x17, 0xb3, 0x05, 0xf6, 0xbc, 0xbe, 0x77, 0x7c, 0x6b, 0xa2, 0xbe, 0xe9, 0xbb, 0x00,
	0x26, 0x66, 0x19, 0x5d, 0x93, 0x1e, 0xec, 0x2f, 0x90, 0x73, 0x36, 0xcf, 0x82, 0x32, 0x93, 0xfe,
	0xe2, 0x41, 0x77, 0x94, 0x22, 0x13, 0x38, 0x0c, 0x82, 0x64, 0x15, 0x8b, 0x2c, 0xe9, 0x7d, 0x68,
	0xb1, 0xe5, 0xf2, 0x33, 0xbc, 0x36, 0x33, 0x8c, 0x45, 0xba, 0xd0, 0xc4, 0x05, 0x0b, 0xa3, 0x5e,
	0x5d, 0xb9, 0xb5, 0x41, 0x7c, 0x68, 0x2f, 0x19, 0xe7, 0x57, 0x49, 0x3a, 0xeb, 0x35, 0xd4, 0xc0,
	0x8d, 0x4d, 0x1e, 0xc0, 0xad, 0x8b, 0x30, 0xe5, 0x62, 0x2c, 0x31, 0xee, 0xa9, 0xc1, 0xb5, 0x43,
	0xce, 0x8c, 0x98, 0x19, 0x6c, 0xea, 0x99, 0x99, 0x4d, 0x4f, 0x81, 0x38, 0xd8, 0x24, 0x99, 0x27,
	0xd0, 0xe2, 0x82, 0x89, 0x15, 0x57, 0x2b, 0x1d, 0x9c, 0x74, 0x07, 0xb6, 0x3a, 0x83, 0xa9, 0x1a,
	0x9b, 0x98, 0x18, 0xfa, 0x35, 0x74, 0x3e, 0x4f, 0xe6, 0x61, 0xfc, 0x8f, 0xf3, 0xa2, 0xbf, 0x7b,
	0x00, 0x26, 0xb5, 0x84, 0xd5, 0x87, 0x03, 0x16, 0x04, 0xc8, 0xf9, 0x17, 0xc9, 0xf7, 0x18, 0x9b,
	0xec, 0xb6, 0x8b, 0x50, 0xe8, 0xa4, 0x78, 0x91, 0x22, 0xbf, 0xd4, 0x21, 0x7a, 0xa5, 0x9c, 0x2f,
	0x2f, 0x56, 0x63, 0x9b, 0x58, 0x7b, 0x79, 0xb1, 0xd6, 0x04, 0x9a, 0x36, 0x81, 0xb5, 0x58, 0xad,
	0x0a, 0x62, 0xcd, 0xa0, 0x6b, 0xa4, 0x1e, 0xae, 0xc4, 0x25, 0x56, 0x17, 0x6d, 0xcf, 0x5e, 0xf3,
	0x11, 0x00, 0x53, 0xd3, 0x47, 0xc9, 0x2c, 0xdb, 0x54, 0xcb, 0x43, 0xff, 0xf0, 0x80, 0x38, 0xcb,
	0xfc, 0x57, 0x04, 0xfc, 0xd3, 0x83, 0xbb, 0xfa, 0xc8, 0x9e, 0x27, 0xfc, 0x8d, 0x77, 0xc9, 0x61,
	0x5c, 0x2f, 0x32, 0xee, 0x42, 0x53, 0x84, 0x22, 0xca, 0x98, 0x68, 0x43, 0x5e, 0x67, 0xbe, 0xc4,
	0x20, 0x44, 0x6e, 0x48, 0x64, 0xa6, 0xcc, 0x38, 0x43, 0x1e, 0xa4, 0xe1, 0x52, 0x84, 0x49, 0x6c,
	0x98, 0xd8, 0x2e, 0x72, 0x07, 0x1a, 0x11, 0x13, 0x8a, 0x4c, 0x7d, 0x22, 0x3f, 0x95, 0x27, 0x9e,
	0xf7, 0xf6, 0x8d, 0x27, 0x9e, 0x4b, 0x9d, 0x31, 0x0e, 0x92, 0x19, 0xce, 0x3e, 0x5d, 0xc8, 0x9a,
	0xd1, 0xd6, 0x3a, 0xdb, 0x3e, 0xfa, 0x0c, 0x6e, 0xdb, 0x44, 0xf3, 0x17, 0xd3, 0xab, 0x74, 0xd6,
	0x0e, 0xcf, 0x50, 0x54, 0x91, 0xc9, 0x40, 0xae, 0x17, 0x20, 0x37, 0xd6, 0x90, 0xef, 0x43, 0x2b,
	0x65, 0xb3, 0x70, 0xa5, 0x15, 0x69, 0x4e, 0x8c, 0x45, 0x05, 0x74, 0x6e, 0x56, 0xd9, 0x19, 0x23,
	0x79, 0x0a, 0xcd, 0x54, 0x4e, 0xeb, 0xd5, 0xfb, 0x8d, 0xe3, 0x83, 0x93, 0x7e, 0x3e, 0xd8, 0x4e,
	0x3c, 0x15, 0xe9, 0x2a, 0x10, 0x13, 0x1d, 0x4e, 0x7f, 0xf3, 0x80, 0x14, 0x47, 0xff, 0xc5, 0xbb,
	0xf9, 0x14, 0x5a, 0x9a, 0xba, 0x7c, 0x4c, 0xd4, 0xb5, 0xf5, 0x94, 0x8c, 0xea, 0x5b, 0x22, 0x7c,
	0x69, 0x9e, 0x0f, 0x7d, 0x46, 0x33, 0x93, 0x4e, 0xe1, 0xe8, 0x0c, 0xc5, 0x70, 0x7d, 0x62, 0xdf,
	0xb4, 0x97, 0x15, 0xae, 0x30, 0x45, 0xb8, 0xe7, 0x26, 0xad, 0x56, 0x1f, 0xd6, 0x9b, 0x5b, 0xaf,
	0x70, 0x00, 0x9f, 0xc3, 0xd1, 0x8b, 0x24, 0x9d, 0xa3, 0x38, 0x37, 0x15, 0xdd, 0xc2, 0x3e, 0xcc,
	0x61, 0x1f, 0x6e, 0x79, 0x22, 0xe8, 0x08, 0xee, 0xb9, 0x69, 0x76, 0xbf, 0x0c, 0x3f, 0xc1, 0xe3,
	0x7c, 0x92, 0x2f, 0x31, 0x0d, 0x2f, 0xae, 0xa5, 0xfa, 0x15, 0x50, 0x3d, 0xb7, 0x51, 0x29, 0x83,
	0xbc, 0x0f, 0x77, 0x54, 0x8a, 0x30, 0x60, 0xf2, 0xa0, 0xa8, 0x2d, 0xd5, 0xa7, 0xae, 0xe0, 0xa7,
	0x2f, 0xe1, 0xe1, 0xe6, 0xc5, 0x77, 0xe7, 0x12, 0x41, 0x3f, 0x9f, 0x6e, 0x8c, 0x57, 0x3b, 0x48,
	0x5c, 0x42, 0xc6, 0x87, 0xf6, 0xb9, 0xf3, 0x0a, 0x67, 0x36, 0x1d, 0xc3, 0xa3, 0x2d, 0xab, 0xed,
	0x8e, 0xfe, 0x57, 0x0f, 0x8e, 0x46, 0x97, 0x2c, 0x9e, 0x63, 0x55, 0xcc, 0x7d, 0x38, 0x18, 0x16,
	0xab, 0xb8, 0xe5, 0x22, 0xc7, 0x70, 0x7b, 0xb4, 0x4a, 0x53, 0x8c, 0x85, 0x43, 0xc3, 0x75, 0xcb,
	0x5c, 0x16, 0x7e, 0x53, 0x0f, 0x6c, 0x97, 0x3c, 0x6e, 0x2e, 0xbc, 0x9d, 0x49, 0x9e, 0xfc, 0xb5,
	0x0f, 0x87, 0x53, 0x4c, 0x7f, 0xc4, 0xd4, 0x90, 0xe3, 0xe4, 0x2b, 0xf8, 0x5f, 0xae, 0xd7, 0x22,
	0x34, 0x9f, 0xa1, 0xac, 0x49, 0xf4, 0xfb, 0x5b, 0x63, 0x64, 0x25, 0xac, 0x91, 0x67, 0xd0, 0x54,
	0x5d, 0x12, 0xf1, 0xf3, 0xc1, 0x76, 0x57, 0xe6, 0xf7, 0x4a, 0xc7, 0x74, 0x82, 0x6f, 0xe1, 0x28,
	0xd7, 0x2d, 0x08, 0x73, 0x76, 0x5d, 0x84, 0x65, 0x9d, 0x8b, 0x8b, 0xb0, 0xd8, 0x76, 0xd0, 0x1a,
	0xf9, 0x06, 0xee, 0x9e, 0xa1, 0x18, 0xe3, 0x95, 0xbd, 0x67, 0xef, 0x14, 0x6a, 0x7d, 0xb1, 0xca,
	0xf9, 0x6f, 0x6f, 0x0f, 0xd2, 0xe9, 0x4f, 0xa1, 0x3d, 0x65, 0xd7, 0xaa, 0x1b, 0x77, 0x35, 0xb0,
	0xdb, 0x78, 0x57, 0x83, 0x75, 0xfb, 0x4e, 0x6b, 0x64, 0x0c, 0xb0, 0x7e, 0x6d, 0xc9, 0xe3, 0x32,
	0xd9, 0xad, 0x97, 0xd4, 0x7f, 0xb8, 0x39, 0x40, 0xe7, 0x7b, 0x01, 0x6d, 0xf3, 0x3e, 0x71, 0xf2,
	0x60, 0xc3, 0xab, 0xa6, 0x53, 0xf9, 0x9b, 0xdf, 0x3c, 0x5a, 0x23, 0xaf, 0xe0, 0x30, 0x7f, 0xfb,
	0x5c, 0xdd, 0x4a, 0x2b, 0xac, 0xab, 0x5b, 0x49, 0xfd, 0xa4, 0x35, 0xf2, 0x1a, 0x7a, 0x9b, 0xca,
	0x12, 0xf9, 0x70, 0x5b, 0x82, 0x42, 0xed, 0xf4, 0x3f, 0xa8, 0x1a, 0xae, 0x57, 0xfe, 0x19, 0xde,
	0x72, 0x21, 0x71, 0x8b, 0xe2, 0x60, 0x5b, 0xb6, 0x62, 0xb1, 0xf3, 0x9f, 0x54, 0x8e, 0xbf, 0x11,
	0x35, 0x7f, 0xc5, 0x5d, 0x51, 0x4b, 0xeb, 0x93, 0x2b, 0x6a, 0x49, 0x95, 0xa0, 0xb5, 0xd3, 0xf7,
	0xe0, 0xff, 0x41, 0xb2, 0x18, 0xe0, 0x6b, 0xb6, 0x58, 0x46, 0xc8, 0x73, 0x53, 0x5e, 0xe5, 0xfe,
	0x66, 0x7e, 0xd7, 0x52, 0x3f, 0x1f, 0xff, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x52, 0xff, 0x82, 0x8f,
	0x99, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServerRequestsClient is the client API for ServerRequests service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerRequestsClient interface {
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountReply, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	AccountAuthentication(ctx context.Context, in *AccountAuthenRequest, opts ...grpc.CallOption) (*AccountAuthenReply, error)
	GetNewAccessToken(ctx context.Context, in *GetAccessTokenRequest, opts ...grpc.CallOption) (*GetAccessTokenReply, error)
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostReply, error)
	GetPosts(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostReply, error)
	ForgetPassword(ctx context.Context, in *ForgetPasswordRequest, opts ...grpc.CallOption) (*ForgetPasswordReply, error)
	ForgetPasswordVerifyCode(ctx context.Context, in *ForgetPasswordVerifyCodeRequest, opts ...grpc.CallOption) (*ForgetPasswordVerifyCodeReply, error)
	ForgetPasswordResetPassword(ctx context.Context, in *ForgetPasswordNewPasswordRequest, opts ...grpc.CallOption) (*ForgetPasswordNewPasswordReply, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordReply, error)
}

type serverRequestsClient struct {
	cc *grpc.ClientConn
}

func NewServerRequestsClient(cc *grpc.ClientConn) ServerRequestsClient {
	return &serverRequestsClient{cc}
}

func (c *serverRequestsClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountReply, error) {
	out := new(CreateAccountReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) AccountAuthentication(ctx context.Context, in *AccountAuthenRequest, opts ...grpc.CallOption) (*AccountAuthenReply, error) {
	out := new(AccountAuthenReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/AccountAuthentication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) GetNewAccessToken(ctx context.Context, in *GetAccessTokenRequest, opts ...grpc.CallOption) (*GetAccessTokenReply, error) {
	out := new(GetAccessTokenReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/GetNewAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostReply, error) {
	out := new(CreatePostReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) GetPosts(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostReply, error) {
	out := new(GetPostReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/GetPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) ForgetPassword(ctx context.Context, in *ForgetPasswordRequest, opts ...grpc.CallOption) (*ForgetPasswordReply, error) {
	out := new(ForgetPasswordReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/ForgetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) ForgetPasswordVerifyCode(ctx context.Context, in *ForgetPasswordVerifyCodeRequest, opts ...grpc.CallOption) (*ForgetPasswordVerifyCodeReply, error) {
	out := new(ForgetPasswordVerifyCodeReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/ForgetPasswordVerifyCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) ForgetPasswordResetPassword(ctx context.Context, in *ForgetPasswordNewPasswordRequest, opts ...grpc.CallOption) (*ForgetPasswordNewPasswordReply, error) {
	out := new(ForgetPasswordNewPasswordReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/ForgetPasswordResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordReply, error) {
	out := new(ChangePasswordReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerRequestsServer is the server API for ServerRequests service.
type ServerRequestsServer interface {
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountReply, error)
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	AccountAuthentication(context.Context, *AccountAuthenRequest) (*AccountAuthenReply, error)
	GetNewAccessToken(context.Context, *GetAccessTokenRequest) (*GetAccessTokenReply, error)
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	CreatePost(context.Context, *CreatePostRequest) (*CreatePostReply, error)
	GetPosts(context.Context, *GetPostRequest) (*GetPostReply, error)
	ForgetPassword(context.Context, *ForgetPasswordRequest) (*ForgetPasswordReply, error)
	ForgetPasswordVerifyCode(context.Context, *ForgetPasswordVerifyCodeRequest) (*ForgetPasswordVerifyCodeReply, error)
	ForgetPasswordResetPassword(context.Context, *ForgetPasswordNewPasswordRequest) (*ForgetPasswordNewPasswordReply, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordReply, error)
}

func RegisterServerRequestsServer(s *grpc.Server, srv ServerRequestsServer) {
	s.RegisterService(&_ServerRequests_serviceDesc, srv)
}

func _ServerRequests_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_AccountAuthentication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountAuthenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).AccountAuthentication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/AccountAuthentication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).AccountAuthentication(ctx, req.(*AccountAuthenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_GetNewAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).GetNewAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/GetNewAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).GetNewAccessToken(ctx, req.(*GetAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_GetPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).GetPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/GetPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).GetPosts(ctx, req.(*GetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_ForgetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).ForgetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/ForgetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).ForgetPassword(ctx, req.(*ForgetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_ForgetPasswordVerifyCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgetPasswordVerifyCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).ForgetPasswordVerifyCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/ForgetPasswordVerifyCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).ForgetPasswordVerifyCode(ctx, req.(*ForgetPasswordVerifyCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_ForgetPasswordResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgetPasswordNewPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).ForgetPasswordResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/ForgetPasswordResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).ForgetPasswordResetPassword(ctx, req.(*ForgetPasswordNewPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServerRequests_serviceDesc = grpc.ServiceDesc{
	ServiceName: "naturaeproto.ServerRequests",
	HandlerType: (*ServerRequestsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _ServerRequests_CreateAccount_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _ServerRequests_Login_Handler,
		},
		{
			MethodName: "AccountAuthentication",
			Handler:    _ServerRequests_AccountAuthentication_Handler,
		},
		{
			MethodName: "GetNewAccessToken",
			Handler:    _ServerRequests_GetNewAccessToken_Handler,
		},
		{
			MethodName: "SayHello",
			Handler:    _ServerRequests_SayHello_Handler,
		},
		{
			MethodName: "CreatePost",
			Handler:    _ServerRequests_CreatePost_Handler,
		},
		{
			MethodName: "GetPosts",
			Handler:    _ServerRequests_GetPosts_Handler,
		},
		{
			MethodName: "ForgetPassword",
			Handler:    _ServerRequests_ForgetPassword_Handler,
		},
		{
			MethodName: "ForgetPasswordVerifyCode",
			Handler:    _ServerRequests_ForgetPasswordVerifyCode_Handler,
		},
		{
			MethodName: "ForgetPasswordResetPassword",
			Handler:    _ServerRequests_ForgetPasswordResetPassword_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _ServerRequests_ChangePassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "naturaeproto/Naturae.proto",
}
