// Code generated by protoc-gen-go. DO NOT EDIT.
// source: naturaeproto/Naturae.proto

package naturaeproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CreateAccountRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=appKey,proto3" json:"appKey,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	FirstName            string   `protobuf:"bytes,4,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,5,opt,name=lastName,proto3" json:"lastName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{2}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *CreateAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateAccountRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateAccountRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type CreateAccountReply struct {
	Status               *Status  `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountReply) Reset()         { *m = CreateAccountReply{} }
func (m *CreateAccountReply) String() string { return proto.CompactTextString(m) }
func (*CreateAccountReply) ProtoMessage()    {}
func (*CreateAccountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{3}
}

func (m *CreateAccountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountReply.Unmarshal(m, b)
}
func (m *CreateAccountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountReply.Marshal(b, m, deterministic)
}
func (m *CreateAccountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountReply.Merge(m, src)
}
func (m *CreateAccountReply) XXX_Size() int {
	return xxx_messageInfo_CreateAccountReply.Size(m)
}
func (m *CreateAccountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountReply proto.InternalMessageInfo

func (m *CreateAccountReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type LoginRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=appKey,proto3" json:"appKey,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{4}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginReply struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Status               *Status  `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{5}
}

func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (m *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(m, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

func (m *LoginReply) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *LoginReply) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *LoginReply) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *LoginReply) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *LoginReply) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type AccountAuthenRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=appKey,proto3" json:"appKey,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	AuthenCode           string   `protobuf:"bytes,4,opt,name=authenCode,proto3" json:"authenCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountAuthenRequest) Reset()         { *m = AccountAuthenRequest{} }
func (m *AccountAuthenRequest) String() string { return proto.CompactTextString(m) }
func (*AccountAuthenRequest) ProtoMessage()    {}
func (*AccountAuthenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{6}
}

func (m *AccountAuthenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountAuthenRequest.Unmarshal(m, b)
}
func (m *AccountAuthenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountAuthenRequest.Marshal(b, m, deterministic)
}
func (m *AccountAuthenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountAuthenRequest.Merge(m, src)
}
func (m *AccountAuthenRequest) XXX_Size() int {
	return xxx_messageInfo_AccountAuthenRequest.Size(m)
}
func (m *AccountAuthenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountAuthenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountAuthenRequest proto.InternalMessageInfo

func (m *AccountAuthenRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *AccountAuthenRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *AccountAuthenRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AccountAuthenRequest) GetAuthenCode() string {
	if m != nil {
		return m.AuthenCode
	}
	return ""
}

type AccountAuthenReply struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Status               *Status  `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountAuthenReply) Reset()         { *m = AccountAuthenReply{} }
func (m *AccountAuthenReply) String() string { return proto.CompactTextString(m) }
func (*AccountAuthenReply) ProtoMessage()    {}
func (*AccountAuthenReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{7}
}

func (m *AccountAuthenReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountAuthenReply.Unmarshal(m, b)
}
func (m *AccountAuthenReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountAuthenReply.Marshal(b, m, deterministic)
}
func (m *AccountAuthenReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountAuthenReply.Merge(m, src)
}
func (m *AccountAuthenReply) XXX_Size() int {
	return xxx_messageInfo_AccountAuthenReply.Size(m)
}
func (m *AccountAuthenReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountAuthenReply.DiscardUnknown(m)
}

var xxx_messageInfo_AccountAuthenReply proto.InternalMessageInfo

func (m *AccountAuthenReply) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AccountAuthenReply) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *AccountAuthenReply) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *AccountAuthenReply) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *AccountAuthenReply) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AccountAuthenReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type CreatePostRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=appKey,proto3" json:"appKey,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Species              string   `protobuf:"bytes,4,opt,name=species,proto3" json:"species,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Lat                  float32  `protobuf:"fixed32,6,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float32  `protobuf:"fixed32,7,opt,name=lng,proto3" json:"lng,omitempty"`
	EncodedImage         string   `protobuf:"bytes,8,opt,name=encodedImage,proto3" json:"encodedImage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{8}
}

func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(m, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *CreatePostRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *CreatePostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreatePostRequest) GetSpecies() string {
	if m != nil {
		return m.Species
	}
	return ""
}

func (m *CreatePostRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreatePostRequest) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *CreatePostRequest) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *CreatePostRequest) GetEncodedImage() string {
	if m != nil {
		return m.EncodedImage
	}
	return ""
}

type CreatePostReply struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostReply) Reset()         { *m = CreatePostReply{} }
func (m *CreatePostReply) String() string { return proto.CompactTextString(m) }
func (*CreatePostReply) ProtoMessage()    {}
func (*CreatePostReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{9}
}

func (m *CreatePostReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostReply.Unmarshal(m, b)
}
func (m *CreatePostReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostReply.Marshal(b, m, deterministic)
}
func (m *CreatePostReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostReply.Merge(m, src)
}
func (m *CreatePostReply) XXX_Size() int {
	return xxx_messageInfo_CreatePostReply.Size(m)
}
func (m *CreatePostReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostReply proto.InternalMessageInfo

func (m *CreatePostReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetPostRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=appKey,proto3" json:"appKey,omitempty"`
	Lat                  float32  `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float32  `protobuf:"fixed32,3,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostRequest) Reset()         { *m = GetPostRequest{} }
func (m *GetPostRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostRequest) ProtoMessage()    {}
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{10}
}

func (m *GetPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostRequest.Unmarshal(m, b)
}
func (m *GetPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostRequest.Marshal(b, m, deterministic)
}
func (m *GetPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostRequest.Merge(m, src)
}
func (m *GetPostRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostRequest.Size(m)
}
func (m *GetPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostRequest proto.InternalMessageInfo

func (m *GetPostRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *GetPostRequest) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *GetPostRequest) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

type GetPostPreviewRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=appKey,proto3" json:"appKey,omitempty"`
	Lat                  float32  `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float32  `protobuf:"fixed32,3,opt,name=lng,proto3" json:"lng,omitempty"`
	Radius               int32    `protobuf:"varint,4,opt,name=radius,proto3" json:"radius,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostPreviewRequest) Reset()         { *m = GetPostPreviewRequest{} }
func (m *GetPostPreviewRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostPreviewRequest) ProtoMessage()    {}
func (*GetPostPreviewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{11}
}

func (m *GetPostPreviewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostPreviewRequest.Unmarshal(m, b)
}
func (m *GetPostPreviewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostPreviewRequest.Marshal(b, m, deterministic)
}
func (m *GetPostPreviewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostPreviewRequest.Merge(m, src)
}
func (m *GetPostPreviewRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostPreviewRequest.Size(m)
}
func (m *GetPostPreviewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostPreviewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostPreviewRequest proto.InternalMessageInfo

func (m *GetPostPreviewRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *GetPostPreviewRequest) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *GetPostPreviewRequest) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *GetPostPreviewRequest) GetRadius() int32 {
	if m != nil {
		return m.Radius
	}
	return 0
}

type GetPostPreviewReply struct {
	Status               *Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Reply                []*PostStruct `protobuf:"bytes,2,rep,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetPostPreviewReply) Reset()         { *m = GetPostPreviewReply{} }
func (m *GetPostPreviewReply) String() string { return proto.CompactTextString(m) }
func (*GetPostPreviewReply) ProtoMessage()    {}
func (*GetPostPreviewReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{12}
}

func (m *GetPostPreviewReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostPreviewReply.Unmarshal(m, b)
}
func (m *GetPostPreviewReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostPreviewReply.Marshal(b, m, deterministic)
}
func (m *GetPostPreviewReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostPreviewReply.Merge(m, src)
}
func (m *GetPostPreviewReply) XXX_Size() int {
	return xxx_messageInfo_GetPostPreviewReply.Size(m)
}
func (m *GetPostPreviewReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostPreviewReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostPreviewReply proto.InternalMessageInfo

func (m *GetPostPreviewReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetPostPreviewReply) GetReply() []*PostStruct {
	if m != nil {
		return m.Reply
	}
	return nil
}

type GetPostReply struct {
	Status               *Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Reply                []*PostStruct `protobuf:"bytes,2,rep,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetPostReply) Reset()         { *m = GetPostReply{} }
func (m *GetPostReply) String() string { return proto.CompactTextString(m) }
func (*GetPostReply) ProtoMessage()    {}
func (*GetPostReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{13}
}

func (m *GetPostReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostReply.Unmarshal(m, b)
}
func (m *GetPostReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostReply.Marshal(b, m, deterministic)
}
func (m *GetPostReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostReply.Merge(m, src)
}
func (m *GetPostReply) XXX_Size() int {
	return xxx_messageInfo_GetPostReply.Size(m)
}
func (m *GetPostReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostReply proto.InternalMessageInfo

func (m *GetPostReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetPostReply) GetReply() []*PostStruct {
	if m != nil {
		return m.Reply
	}
	return nil
}

type PostStruct struct {
	PostID               string   `protobuf:"bytes,1,opt,name=postID,proto3" json:"postID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Species              string   `protobuf:"bytes,3,opt,name=species,proto3" json:"species,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Latitude             float32  `protobuf:"fixed32,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	EncodedImage         string   `protobuf:"bytes,7,opt,name=encodedImage,proto3" json:"encodedImage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostStruct) Reset()         { *m = PostStruct{} }
func (m *PostStruct) String() string { return proto.CompactTextString(m) }
func (*PostStruct) ProtoMessage()    {}
func (*PostStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{14}
}

func (m *PostStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostStruct.Unmarshal(m, b)
}
func (m *PostStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostStruct.Marshal(b, m, deterministic)
}
func (m *PostStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostStruct.Merge(m, src)
}
func (m *PostStruct) XXX_Size() int {
	return xxx_messageInfo_PostStruct.Size(m)
}
func (m *PostStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_PostStruct.DiscardUnknown(m)
}

var xxx_messageInfo_PostStruct proto.InternalMessageInfo

func (m *PostStruct) GetPostID() string {
	if m != nil {
		return m.PostID
	}
	return ""
}

func (m *PostStruct) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PostStruct) GetSpecies() string {
	if m != nil {
		return m.Species
	}
	return ""
}

func (m *PostStruct) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PostStruct) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *PostStruct) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *PostStruct) GetEncodedImage() string {
	if m != nil {
		return m.EncodedImage
	}
	return ""
}

type SearchPostRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=appKey,proto3" json:"appKey,omitempty"`
	Search               string   `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	FilterType           string   `protobuf:"bytes,3,opt,name=filterType,proto3" json:"filterType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchPostRequest) Reset()         { *m = SearchPostRequest{} }
func (m *SearchPostRequest) String() string { return proto.CompactTextString(m) }
func (*SearchPostRequest) ProtoMessage()    {}
func (*SearchPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{15}
}

func (m *SearchPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchPostRequest.Unmarshal(m, b)
}
func (m *SearchPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchPostRequest.Marshal(b, m, deterministic)
}
func (m *SearchPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchPostRequest.Merge(m, src)
}
func (m *SearchPostRequest) XXX_Size() int {
	return xxx_messageInfo_SearchPostRequest.Size(m)
}
func (m *SearchPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchPostRequest proto.InternalMessageInfo

func (m *SearchPostRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *SearchPostRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *SearchPostRequest) GetFilterType() string {
	if m != nil {
		return m.FilterType
	}
	return ""
}

type SearchPostReply struct {
	Status               *Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Reply                []*PostStruct `protobuf:"bytes,2,rep,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SearchPostReply) Reset()         { *m = SearchPostReply{} }
func (m *SearchPostReply) String() string { return proto.CompactTextString(m) }
func (*SearchPostReply) ProtoMessage()    {}
func (*SearchPostReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{16}
}

func (m *SearchPostReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchPostReply.Unmarshal(m, b)
}
func (m *SearchPostReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchPostReply.Marshal(b, m, deterministic)
}
func (m *SearchPostReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchPostReply.Merge(m, src)
}
func (m *SearchPostReply) XXX_Size() int {
	return xxx_messageInfo_SearchPostReply.Size(m)
}
func (m *SearchPostReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchPostReply.DiscardUnknown(m)
}

var xxx_messageInfo_SearchPostReply proto.InternalMessageInfo

func (m *SearchPostReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SearchPostReply) GetReply() []*PostStruct {
	if m != nil {
		return m.Reply
	}
	return nil
}

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{17}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

//Both values can be processed by the server to search for a list of users, their usage is mutually exclusive
//If the identifier for the user is used, their friendslist is returned, if a query is sent, all matching registered users are returned
type UserSearchRequest struct {
	// string appKey = 1;
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Query                string   `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSearchRequest) Reset()         { *m = UserSearchRequest{} }
func (m *UserSearchRequest) String() string { return proto.CompactTextString(m) }
func (*UserSearchRequest) ProtoMessage()    {}
func (*UserSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{18}
}

func (m *UserSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSearchRequest.Unmarshal(m, b)
}
func (m *UserSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSearchRequest.Marshal(b, m, deterministic)
}
func (m *UserSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSearchRequest.Merge(m, src)
}
func (m *UserSearchRequest) XXX_Size() int {
	return xxx_messageInfo_UserSearchRequest.Size(m)
}
func (m *UserSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserSearchRequest proto.InternalMessageInfo

func (m *UserSearchRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *UserSearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

//A list of users that matched the parameters provided by the UserSearchRequest
type UserListReply struct {
	Users                []string `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListReply) Reset()         { *m = UserListReply{} }
func (m *UserListReply) String() string { return proto.CompactTextString(m) }
func (*UserListReply) ProtoMessage()    {}
func (*UserListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{19}
}

func (m *UserListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListReply.Unmarshal(m, b)
}
func (m *UserListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListReply.Marshal(b, m, deterministic)
}
func (m *UserListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListReply.Merge(m, src)
}
func (m *UserListReply) XXX_Size() int {
	return xxx_messageInfo_UserListReply.Size(m)
}
func (m *UserListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListReply.DiscardUnknown(m)
}

var xxx_messageInfo_UserListReply proto.InternalMessageInfo

func (m *UserListReply) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *UserListReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

// The request message containing the users's to perform an action on
type FriendRequest struct {
	//string appKey = 1;
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver             string   `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendRequest) Reset()         { *m = FriendRequest{} }
func (m *FriendRequest) String() string { return proto.CompactTextString(m) }
func (*FriendRequest) ProtoMessage()    {}
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{20}
}

func (m *FriendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendRequest.Unmarshal(m, b)
}
func (m *FriendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendRequest.Marshal(b, m, deterministic)
}
func (m *FriendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendRequest.Merge(m, src)
}
func (m *FriendRequest) XXX_Size() int {
	return xxx_messageInfo_FriendRequest.Size(m)
}
func (m *FriendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FriendRequest proto.InternalMessageInfo

func (m *FriendRequest) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *FriendRequest) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

//The reply message from the server
type FriendReply struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendReply) Reset()         { *m = FriendReply{} }
func (m *FriendReply) String() string { return proto.CompactTextString(m) }
func (*FriendReply) ProtoMessage()    {}
func (*FriendReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{21}
}

func (m *FriendReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendReply.Unmarshal(m, b)
}
func (m *FriendReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendReply.Marshal(b, m, deterministic)
}
func (m *FriendReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendReply.Merge(m, src)
}
func (m *FriendReply) XXX_Size() int {
	return xxx_messageInfo_FriendReply.Size(m)
}
func (m *FriendReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendReply.DiscardUnknown(m)
}

var xxx_messageInfo_FriendReply proto.InternalMessageInfo

func (m *FriendReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

//
//message ChatlogRequest{
//repeated ChatMessage = 1;
//}
//message ChatMessage{
//string userWhoSentIt = 1;
//string messageBody = 2;
//long timestampSent = 3;
//}
//
//message ChatlogReply{
//repeated ChatMessage = 1;
//}
type RoomRequest struct {
	UserOwner1           string   `protobuf:"bytes,1,opt,name=userOwner1,proto3" json:"userOwner1,omitempty"`
	UserOwner2           string   `protobuf:"bytes,2,opt,name=userOwner2,proto3" json:"userOwner2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomRequest) Reset()         { *m = RoomRequest{} }
func (m *RoomRequest) String() string { return proto.CompactTextString(m) }
func (*RoomRequest) ProtoMessage()    {}
func (*RoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{22}
}

func (m *RoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomRequest.Unmarshal(m, b)
}
func (m *RoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomRequest.Marshal(b, m, deterministic)
}
func (m *RoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomRequest.Merge(m, src)
}
func (m *RoomRequest) XXX_Size() int {
	return xxx_messageInfo_RoomRequest.Size(m)
}
func (m *RoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomRequest proto.InternalMessageInfo

func (m *RoomRequest) GetUserOwner1() string {
	if m != nil {
		return m.UserOwner1
	}
	return ""
}

func (m *RoomRequest) GetUserOwner2() string {
	if m != nil {
		return m.UserOwner2
	}
	return ""
}

type RoomReply struct {
	RoomName             string   `protobuf:"bytes,1,opt,name=roomName,proto3" json:"roomName,omitempty"`
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomReply) Reset()         { *m = RoomReply{} }
func (m *RoomReply) String() string { return proto.CompactTextString(m) }
func (*RoomReply) ProtoMessage()    {}
func (*RoomReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{23}
}

func (m *RoomReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomReply.Unmarshal(m, b)
}
func (m *RoomReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomReply.Marshal(b, m, deterministic)
}
func (m *RoomReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomReply.Merge(m, src)
}
func (m *RoomReply) XXX_Size() int {
	return xxx_messageInfo_RoomReply.Size(m)
}
func (m *RoomReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomReply.DiscardUnknown(m)
}

var xxx_messageInfo_RoomReply proto.InternalMessageInfo

func (m *RoomReply) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *RoomReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetAccessTokenRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=appKey,proto3" json:"appKey,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccessTokenRequest) Reset()         { *m = GetAccessTokenRequest{} }
func (m *GetAccessTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenRequest) ProtoMessage()    {}
func (*GetAccessTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{24}
}

func (m *GetAccessTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenRequest.Unmarshal(m, b)
}
func (m *GetAccessTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetAccessTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenRequest.Merge(m, src)
}
func (m *GetAccessTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenRequest.Size(m)
}
func (m *GetAccessTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenRequest proto.InternalMessageInfo

func (m *GetAccessTokenRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *GetAccessTokenRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type GetAccessTokenReply struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccessTokenReply) Reset()         { *m = GetAccessTokenReply{} }
func (m *GetAccessTokenReply) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenReply) ProtoMessage()    {}
func (*GetAccessTokenReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{25}
}

func (m *GetAccessTokenReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenReply.Unmarshal(m, b)
}
func (m *GetAccessTokenReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenReply.Marshal(b, m, deterministic)
}
func (m *GetAccessTokenReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenReply.Merge(m, src)
}
func (m *GetAccessTokenReply) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenReply.Size(m)
}
func (m *GetAccessTokenReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenReply proto.InternalMessageInfo

func (m *GetAccessTokenReply) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetAccessTokenReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type ForgetPasswordRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=AppKey,proto3" json:"AppKey,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetPasswordRequest) Reset()         { *m = ForgetPasswordRequest{} }
func (m *ForgetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgetPasswordRequest) ProtoMessage()    {}
func (*ForgetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{26}
}

func (m *ForgetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetPasswordRequest.Unmarshal(m, b)
}
func (m *ForgetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ForgetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetPasswordRequest.Merge(m, src)
}
func (m *ForgetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgetPasswordRequest.Size(m)
}
func (m *ForgetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetPasswordRequest proto.InternalMessageInfo

func (m *ForgetPasswordRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *ForgetPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ForgetPasswordReply struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetPasswordReply) Reset()         { *m = ForgetPasswordReply{} }
func (m *ForgetPasswordReply) String() string { return proto.CompactTextString(m) }
func (*ForgetPasswordReply) ProtoMessage()    {}
func (*ForgetPasswordReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{27}
}

func (m *ForgetPasswordReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetPasswordReply.Unmarshal(m, b)
}
func (m *ForgetPasswordReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetPasswordReply.Marshal(b, m, deterministic)
}
func (m *ForgetPasswordReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetPasswordReply.Merge(m, src)
}
func (m *ForgetPasswordReply) XXX_Size() int {
	return xxx_messageInfo_ForgetPasswordReply.Size(m)
}
func (m *ForgetPasswordReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetPasswordReply.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetPasswordReply proto.InternalMessageInfo

func (m *ForgetPasswordReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type ForgetPasswordVerifyCodeRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=AppKey,proto3" json:"AppKey,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	VerificationCode     string   `protobuf:"bytes,3,opt,name=VerificationCode,proto3" json:"VerificationCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetPasswordVerifyCodeRequest) Reset()         { *m = ForgetPasswordVerifyCodeRequest{} }
func (m *ForgetPasswordVerifyCodeRequest) String() string { return proto.CompactTextString(m) }
func (*ForgetPasswordVerifyCodeRequest) ProtoMessage()    {}
func (*ForgetPasswordVerifyCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{28}
}

func (m *ForgetPasswordVerifyCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetPasswordVerifyCodeRequest.Unmarshal(m, b)
}
func (m *ForgetPasswordVerifyCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetPasswordVerifyCodeRequest.Marshal(b, m, deterministic)
}
func (m *ForgetPasswordVerifyCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetPasswordVerifyCodeRequest.Merge(m, src)
}
func (m *ForgetPasswordVerifyCodeRequest) XXX_Size() int {
	return xxx_messageInfo_ForgetPasswordVerifyCodeRequest.Size(m)
}
func (m *ForgetPasswordVerifyCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetPasswordVerifyCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetPasswordVerifyCodeRequest proto.InternalMessageInfo

func (m *ForgetPasswordVerifyCodeRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *ForgetPasswordVerifyCodeRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ForgetPasswordVerifyCodeRequest) GetVerificationCode() string {
	if m != nil {
		return m.VerificationCode
	}
	return ""
}

type ForgetPasswordVerifyCodeReply struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetPasswordVerifyCodeReply) Reset()         { *m = ForgetPasswordVerifyCodeReply{} }
func (m *ForgetPasswordVerifyCodeReply) String() string { return proto.CompactTextString(m) }
func (*ForgetPasswordVerifyCodeReply) ProtoMessage()    {}
func (*ForgetPasswordVerifyCodeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{29}
}

func (m *ForgetPasswordVerifyCodeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetPasswordVerifyCodeReply.Unmarshal(m, b)
}
func (m *ForgetPasswordVerifyCodeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetPasswordVerifyCodeReply.Marshal(b, m, deterministic)
}
func (m *ForgetPasswordVerifyCodeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetPasswordVerifyCodeReply.Merge(m, src)
}
func (m *ForgetPasswordVerifyCodeReply) XXX_Size() int {
	return xxx_messageInfo_ForgetPasswordVerifyCodeReply.Size(m)
}
func (m *ForgetPasswordVerifyCodeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetPasswordVerifyCodeReply.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetPasswordVerifyCodeReply proto.InternalMessageInfo

func (m *ForgetPasswordVerifyCodeReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type ForgetPasswordNewPasswordRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=AppKey,proto3" json:"AppKey,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetPasswordNewPasswordRequest) Reset()         { *m = ForgetPasswordNewPasswordRequest{} }
func (m *ForgetPasswordNewPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgetPasswordNewPasswordRequest) ProtoMessage()    {}
func (*ForgetPasswordNewPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{30}
}

func (m *ForgetPasswordNewPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetPasswordNewPasswordRequest.Unmarshal(m, b)
}
func (m *ForgetPasswordNewPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetPasswordNewPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ForgetPasswordNewPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetPasswordNewPasswordRequest.Merge(m, src)
}
func (m *ForgetPasswordNewPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgetPasswordNewPasswordRequest.Size(m)
}
func (m *ForgetPasswordNewPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetPasswordNewPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetPasswordNewPasswordRequest proto.InternalMessageInfo

func (m *ForgetPasswordNewPasswordRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *ForgetPasswordNewPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ForgetPasswordNewPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ForgetPasswordNewPasswordReply struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetPasswordNewPasswordReply) Reset()         { *m = ForgetPasswordNewPasswordReply{} }
func (m *ForgetPasswordNewPasswordReply) String() string { return proto.CompactTextString(m) }
func (*ForgetPasswordNewPasswordReply) ProtoMessage()    {}
func (*ForgetPasswordNewPasswordReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{31}
}

func (m *ForgetPasswordNewPasswordReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetPasswordNewPasswordReply.Unmarshal(m, b)
}
func (m *ForgetPasswordNewPasswordReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetPasswordNewPasswordReply.Marshal(b, m, deterministic)
}
func (m *ForgetPasswordNewPasswordReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetPasswordNewPasswordReply.Merge(m, src)
}
func (m *ForgetPasswordNewPasswordReply) XXX_Size() int {
	return xxx_messageInfo_ForgetPasswordNewPasswordReply.Size(m)
}
func (m *ForgetPasswordNewPasswordReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetPasswordNewPasswordReply.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetPasswordNewPasswordReply proto.InternalMessageInfo

func (m *ForgetPasswordNewPasswordReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type ChangePasswordRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=AppKey,proto3" json:"AppKey,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	CurrentPassword      string   `protobuf:"bytes,3,opt,name=CurrentPassword,proto3" json:"CurrentPassword,omitempty"`
	NewPassword          string   `protobuf:"bytes,4,opt,name=NewPassword,proto3" json:"NewPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{32}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *ChangePasswordRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *ChangePasswordRequest) GetCurrentPassword() string {
	if m != nil {
		return m.CurrentPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ChangePasswordReply struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordReply) Reset()         { *m = ChangePasswordReply{} }
func (m *ChangePasswordReply) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordReply) ProtoMessage()    {}
func (*ChangePasswordReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{33}
}

func (m *ChangePasswordReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordReply.Unmarshal(m, b)
}
func (m *ChangePasswordReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordReply.Marshal(b, m, deterministic)
}
func (m *ChangePasswordReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordReply.Merge(m, src)
}
func (m *ChangePasswordReply) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordReply.Size(m)
}
func (m *ChangePasswordReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordReply.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordReply proto.InternalMessageInfo

func (m *ChangePasswordReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type ProfileImageRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=AppKey,proto3" json:"AppKey,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	EncodedImage         string   `protobuf:"bytes,3,opt,name=encodedImage,proto3" json:"encodedImage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileImageRequest) Reset()         { *m = ProfileImageRequest{} }
func (m *ProfileImageRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileImageRequest) ProtoMessage()    {}
func (*ProfileImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{34}
}

func (m *ProfileImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileImageRequest.Unmarshal(m, b)
}
func (m *ProfileImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileImageRequest.Marshal(b, m, deterministic)
}
func (m *ProfileImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileImageRequest.Merge(m, src)
}
func (m *ProfileImageRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileImageRequest.Size(m)
}
func (m *ProfileImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileImageRequest proto.InternalMessageInfo

func (m *ProfileImageRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *ProfileImageRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *ProfileImageRequest) GetEncodedImage() string {
	if m != nil {
		return m.EncodedImage
	}
	return ""
}

type ProfileImageReply struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	EncodedImage         string   `protobuf:"bytes,2,opt,name=encodedImage,proto3" json:"encodedImage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileImageReply) Reset()         { *m = ProfileImageReply{} }
func (m *ProfileImageReply) String() string { return proto.CompactTextString(m) }
func (*ProfileImageReply) ProtoMessage()    {}
func (*ProfileImageReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2b78300d408eb, []int{35}
}

func (m *ProfileImageReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileImageReply.Unmarshal(m, b)
}
func (m *ProfileImageReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileImageReply.Marshal(b, m, deterministic)
}
func (m *ProfileImageReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileImageReply.Merge(m, src)
}
func (m *ProfileImageReply) XXX_Size() int {
	return xxx_messageInfo_ProfileImageReply.Size(m)
}
func (m *ProfileImageReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileImageReply.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileImageReply proto.InternalMessageInfo

func (m *ProfileImageReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ProfileImageReply) GetEncodedImage() string {
	if m != nil {
		return m.EncodedImage
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "naturaeproto.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "naturaeproto.HelloReply")
	proto.RegisterType((*CreateAccountRequest)(nil), "naturaeproto.CreateAccountRequest")
	proto.RegisterType((*CreateAccountReply)(nil), "naturaeproto.CreateAccountReply")
	proto.RegisterType((*LoginRequest)(nil), "naturaeproto.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "naturaeproto.LoginReply")
	proto.RegisterType((*AccountAuthenRequest)(nil), "naturaeproto.AccountAuthenRequest")
	proto.RegisterType((*AccountAuthenReply)(nil), "naturaeproto.AccountAuthenReply")
	proto.RegisterType((*CreatePostRequest)(nil), "naturaeproto.CreatePostRequest")
	proto.RegisterType((*CreatePostReply)(nil), "naturaeproto.CreatePostReply")
	proto.RegisterType((*GetPostRequest)(nil), "naturaeproto.GetPostRequest")
	proto.RegisterType((*GetPostPreviewRequest)(nil), "naturaeproto.GetPostPreviewRequest")
	proto.RegisterType((*GetPostPreviewReply)(nil), "naturaeproto.GetPostPreviewReply")
	proto.RegisterType((*GetPostReply)(nil), "naturaeproto.GetPostReply")
	proto.RegisterType((*PostStruct)(nil), "naturaeproto.PostStruct")
	proto.RegisterType((*SearchPostRequest)(nil), "naturaeproto.SearchPostRequest")
	proto.RegisterType((*SearchPostReply)(nil), "naturaeproto.SearchPostReply")
	proto.RegisterType((*Status)(nil), "naturaeproto.Status")
	proto.RegisterType((*UserSearchRequest)(nil), "naturaeproto.UserSearchRequest")
	proto.RegisterType((*UserListReply)(nil), "naturaeproto.UserListReply")
	proto.RegisterType((*FriendRequest)(nil), "naturaeproto.FriendRequest")
	proto.RegisterType((*FriendReply)(nil), "naturaeproto.FriendReply")
	proto.RegisterType((*RoomRequest)(nil), "naturaeproto.RoomRequest")
	proto.RegisterType((*RoomReply)(nil), "naturaeproto.RoomReply")
	proto.RegisterType((*GetAccessTokenRequest)(nil), "naturaeproto.GetAccessTokenRequest")
	proto.RegisterType((*GetAccessTokenReply)(nil), "naturaeproto.GetAccessTokenReply")
	proto.RegisterType((*ForgetPasswordRequest)(nil), "naturaeproto.ForgetPasswordRequest")
	proto.RegisterType((*ForgetPasswordReply)(nil), "naturaeproto.ForgetPasswordReply")
	proto.RegisterType((*ForgetPasswordVerifyCodeRequest)(nil), "naturaeproto.ForgetPasswordVerifyCodeRequest")
	proto.RegisterType((*ForgetPasswordVerifyCodeReply)(nil), "naturaeproto.ForgetPasswordVerifyCodeReply")
	proto.RegisterType((*ForgetPasswordNewPasswordRequest)(nil), "naturaeproto.ForgetPasswordNewPasswordRequest")
	proto.RegisterType((*ForgetPasswordNewPasswordReply)(nil), "naturaeproto.ForgetPasswordNewPasswordReply")
	proto.RegisterType((*ChangePasswordRequest)(nil), "naturaeproto.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordReply)(nil), "naturaeproto.ChangePasswordReply")
	proto.RegisterType((*ProfileImageRequest)(nil), "naturaeproto.ProfileImageRequest")
	proto.RegisterType((*ProfileImageReply)(nil), "naturaeproto.ProfileImageReply")
}

func init() { proto.RegisterFile("naturaeproto/Naturae.proto", fileDescriptor_bdd2b78300d408eb) }

var fileDescriptor_bdd2b78300d408eb = []byte{
	// 1344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x58, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0xb6, 0x24, 0xcb, 0xb1, 0x47, 0x8a, 0x1d, 0x6f, 0xec, 0xfc, 0x0a, 0x73, 0xf2, 0xbf, 0x05,
	0x8a, 0xb4, 0x4d, 0x55, 0xd4, 0x05, 0x7a, 0x53, 0x14, 0x81, 0xa2, 0xe6, 0x84, 0xda, 0xaa, 0x21,
	0x25, 0x4d, 0x10, 0xa0, 0x28, 0x58, 0x6a, 0x2c, 0x13, 0xa1, 0x48, 0x65, 0x77, 0x65, 0x47, 0x28,
	0x7a, 0xd3, 0xc7, 0x28, 0x90, 0x77, 0xea, 0x45, 0x2f, 0xfa, 0x06, 0x7d, 0x8d, 0x62, 0x0f, 0x94,
	0x96, 0x4b, 0x5a, 0x91, 0x90, 0xe4, 0xa6, 0x57, 0xd2, 0xcc, 0xce, 0xce, 0x7e, 0xdf, 0x70, 0x76,
	0x66, 0x48, 0xf0, 0x62, 0x5f, 0x8c, 0x99, 0x8f, 0x23, 0x96, 0x88, 0xe4, 0x8b, 0x8e, 0x16, 0x9a,
	0x4a, 0x22, 0x75, 0x7b, 0x8d, 0x52, 0xa8, 0x3f, 0xc2, 0x28, 0x4a, 0xba, 0xf8, 0x6a, 0x8c, 0x5c,
	0x10, 0x02, 0xab, 0xb1, 0x3f, 0xc4, 0x46, 0x69, 0xaf, 0x74, 0x7b, 0xa3, 0xab, 0xfe, 0xd3, 0x8f,
	0x01, 0x8c, 0xcd, 0x28, 0x9a, 0x90, 0x06, 0x5c, 0x18, 0x22, 0xe7, 0xfe, 0x20, 0x35, 0x4a, 0x45,
	0xfa, 0x47, 0x09, 0x76, 0xda, 0x0c, 0x7d, 0x81, 0xad, 0x20, 0x48, 0xc6, 0xb1, 0x48, 0x9d, 0x5e,
	0x81, 0x35, 0x7f, 0x34, 0xfa, 0x1e, 0x27, 0x66, 0x87, 0x91, 0xc8, 0x0e, 0x54, 0x71, 0xe8, 0x87,
	0x51, 0xa3, 0xac, 0xd4, 0x5a, 0x20, 0x1e, 0xac, 0x8f, 0x7c, 0xce, 0xcf, 0x12, 0xd6, 0x6f, 0x54,
	0xd4, 0xc2, 0x54, 0x26, 0xd7, 0x61, 0xe3, 0x38, 0x64, 0x5c, 0x74, 0x24, 0xc6, 0x55, 0xb5, 0x38,
	0x53, 0xc8, 0x9d, 0x91, 0x6f, 0x16, 0xab, 0x7a, 0x67, 0x2a, 0xd3, 0x7b, 0x40, 0x1c, 0x6c, 0x92,
	0xcc, 0x1d, 0x58, 0xe3, 0xc2, 0x17, 0x63, 0xae, 0x4e, 0xaa, 0xed, 0xef, 0x34, 0xed, 0xe8, 0x34,
	0x7b, 0x6a, 0xad, 0x6b, 0x6c, 0xe8, 0x73, 0xa8, 0x1f, 0x24, 0x83, 0x30, 0x7e, 0xef, 0xbc, 0xe8,
	0x9f, 0x25, 0x00, 0xe3, 0x5a, 0xc2, 0xda, 0x83, 0x9a, 0x1f, 0x04, 0xc8, 0xf9, 0x93, 0xe4, 0x25,
	0xc6, 0xc6, 0xbb, 0xad, 0x22, 0x14, 0xea, 0x0c, 0x8f, 0x19, 0xf2, 0x13, 0x6d, 0xa2, 0x4f, 0xca,
	0xe8, 0xb2, 0xc1, 0xaa, 0xcc, 0x0b, 0xd6, 0x6a, 0x36, 0x58, 0x33, 0x02, 0x55, 0x9b, 0xc0, 0x2c,
	0x58, 0x6b, 0x0b, 0x04, 0xeb, 0xf7, 0x12, 0xec, 0x98, 0x58, 0xb7, 0xc6, 0xe2, 0x04, 0xdf, 0x1a,
	0xb5, 0x0c, 0xdc, 0xb2, 0x0b, 0x77, 0x0a, 0xa9, 0x62, 0x43, 0xba, 0x09, 0xe0, 0x2b, 0xe7, 0xed,
	0xa4, 0x9f, 0xd2, 0xb0, 0x34, 0xf4, 0xef, 0x12, 0x10, 0x07, 0xc4, 0x7f, 0x25, 0xbe, 0xff, 0x94,
	0x60, 0x5b, 0x67, 0xf4, 0x51, 0xc2, 0xdf, 0x7a, 0xd5, 0x1c, 0xc6, 0xe5, 0x3c, 0xe3, 0x1d, 0xa8,
	0x8a, 0x50, 0x44, 0x29, 0x13, 0x2d, 0xc8, 0xdb, 0xce, 0x47, 0x18, 0x84, 0xc8, 0x0d, 0x89, 0x54,
	0x94, 0x1e, 0xfb, 0xc8, 0x03, 0x16, 0x8e, 0x44, 0x98, 0xc4, 0x86, 0x89, 0xad, 0x22, 0x97, 0xa0,
	0x12, 0xf9, 0x42, 0x91, 0x29, 0x77, 0xe5, 0x5f, 0xa5, 0x89, 0x07, 0x8d, 0x0b, 0x46, 0x13, 0x0f,
	0x64, 0x9c, 0x31, 0x0e, 0x92, 0x3e, 0xf6, 0x1f, 0x0f, 0x65, 0x49, 0x59, 0xd7, 0x71, 0xb6, 0x75,
	0xf4, 0x2e, 0x6c, 0xd9, 0x44, 0xb3, 0xf7, 0xb6, 0xb4, 0x40, 0xa8, 0x0e, 0x60, 0xf3, 0x21, 0x8a,
	0x45, 0xc2, 0x64, 0x20, 0x97, 0x73, 0x90, 0x2b, 0x53, 0xc8, 0xf4, 0x25, 0xec, 0x1a, 0x6f, 0x47,
	0x0c, 0x4f, 0x43, 0x3c, 0x7b, 0x0f, 0x4e, 0xe5, 0x5e, 0xe6, 0xf7, 0xc3, 0xb1, 0x0e, 0x73, 0xb5,
	0x6b, 0x24, 0xca, 0xe1, 0xb2, 0x7b, 0xd8, 0xd2, 0xfc, 0x49, 0x13, 0xaa, 0x4c, 0x6e, 0x6b, 0x94,
	0xf7, 0x2a, 0xb7, 0x6b, 0xfb, 0x8d, 0xac, 0xb1, 0x74, 0xde, 0x13, 0x6c, 0x1c, 0x88, 0xae, 0x36,
	0xa3, 0x11, 0xd4, 0xa7, 0xf1, 0xfa, 0xf0, 0xa7, 0xfd, 0x55, 0x02, 0x98, 0x69, 0x65, 0x24, 0x46,
	0x09, 0x17, 0x8f, 0xbf, 0x4b, 0xa3, 0xa8, 0xa5, 0x59, 0x7e, 0x96, 0xcf, 0xc9, 0xcf, 0xca, 0xdc,
	0xfc, 0x5c, 0xcd, 0xe7, 0xa7, 0xba, 0xa1, 0x22, 0x14, 0xe3, 0xbe, 0x6e, 0x17, 0xe5, 0xee, 0x54,
	0x96, 0x77, 0x3b, 0x4a, 0xe2, 0x81, 0x5e, 0xd4, 0x19, 0x3c, 0x53, 0xe4, 0xb2, 0xf6, 0x42, 0x41,
	0xd6, 0x06, 0xb0, 0xdd, 0x43, 0x9f, 0x05, 0x27, 0x8b, 0xe4, 0xdd, 0x15, 0x58, 0xe3, 0xca, 0xd8,
	0xb0, 0x33, 0x92, 0xac, 0x6f, 0xc7, 0x61, 0x24, 0x90, 0x3d, 0x99, 0x8c, 0xd2, 0x9b, 0x69, 0x69,
	0x68, 0x02, 0x5b, 0xf6, 0x21, 0x1f, 0xfe, 0x61, 0x7d, 0x0d, 0x6b, 0xda, 0x83, 0x9c, 0x14, 0x54,
	0xd1, 0x2d, 0xa9, 0x7c, 0x55, 0xff, 0xe5, 0xd3, 0x38, 0x34, 0xb3, 0x81, 0xe6, 0x91, 0x8a, 0xf4,
	0x5b, 0xd8, 0x7e, 0xca, 0x91, 0x69, 0xb0, 0xd6, 0xb0, 0x31, 0xe6, 0xc8, 0xd2, 0x61, 0x43, 0xfe,
	0x97, 0x8f, 0xf9, 0xd5, 0x18, 0xd9, 0x24, 0x7d, 0xcc, 0x4a, 0xa0, 0x3d, 0xb8, 0x28, 0xb7, 0x1f,
	0x84, 0x29, 0xcb, 0x1d, 0xa8, 0x4a, 0x73, 0x49, 0xb2, 0x22, 0xcd, 0x94, 0x60, 0x71, 0x2f, 0x2f,
	0x50, 0x16, 0xda, 0x70, 0xf1, 0x01, 0x0b, 0x31, 0xee, 0x5b, 0x4f, 0x87, 0x63, 0xdc, 0x9f, 0x22,
	0x32, 0x92, 0x4c, 0x14, 0x86, 0x01, 0x86, 0xa7, 0xc8, 0x0c, 0xac, 0xa9, 0x4c, 0xbf, 0x81, 0x5a,
	0xea, 0x64, 0xf9, 0xc2, 0x74, 0x08, 0xb5, 0x6e, 0x92, 0x0c, 0xd3, 0xf3, 0x6f, 0x02, 0x48, 0x1e,
	0x3f, 0x9c, 0xc5, 0xc8, 0xbe, 0x34, 0x18, 0x2c, 0x4d, 0x66, 0x7d, 0xdf, 0x20, 0xb1, 0x34, 0xf4,
	0x29, 0x6c, 0x68, 0x77, 0x12, 0x89, 0x04, 0x9d, 0x24, 0xc3, 0xce, 0x6c, 0x9a, 0x9b, 0xca, 0x4b,
	0xc6, 0xa9, 0xa7, 0x0a, 0x5e, 0x6b, 0xd6, 0x2b, 0xde, 0x96, 0xcd, 0x0b, 0x34, 0x4f, 0x8a, 0xaa,
	0xb0, 0x65, 0x9c, 0x2e, 0xd6, 0x99, 0x97, 0xc3, 0x7e, 0x1f, 0x76, 0x1f, 0x24, 0x6c, 0x80, 0xe2,
	0xc8, 0x8c, 0x5a, 0x16, 0xf6, 0x56, 0x06, 0x7b, 0x6b, 0xce, 0xec, 0x46, 0xdb, 0x70, 0xd9, 0x75,
	0xb3, 0xfc, 0xd3, 0xfe, 0x15, 0x6e, 0x65, 0x9d, 0xfc, 0x88, 0x2c, 0x3c, 0x9e, 0xc8, 0x9b, 0xb3,
	0x00, 0xaa, 0xfb, 0x36, 0x2a, 0x25, 0x90, 0x4f, 0xe1, 0x92, 0x72, 0x11, 0x06, 0xbe, 0x2c, 0x68,
	0xea, 0x3a, 0xea, 0x1a, 0x91, 0xd3, 0xd3, 0x43, 0xb8, 0x71, 0xfe, 0xe1, 0xcb, 0x73, 0x89, 0x60,
	0x2f, 0xeb, 0xae, 0x83, 0x67, 0x4b, 0x84, 0xb8, 0x80, 0x8c, 0x07, 0xeb, 0x47, 0xce, 0x78, 0x9c,
	0xca, 0xb4, 0x03, 0x37, 0xe7, 0x9c, 0xb6, 0x3c, 0xfa, 0x37, 0x25, 0xd8, 0x6d, 0x9f, 0xf8, 0xf1,
	0x00, 0x17, 0xc5, 0xbc, 0x07, 0xb5, 0x56, 0x7e, 0x7e, 0xb2, 0x54, 0xe4, 0x36, 0x6c, 0xb5, 0xc7,
	0x8c, 0x61, 0x2c, 0x1c, 0x1a, 0xae, 0x5a, 0xfa, 0xb2, 0xf0, 0xa7, 0x9d, 0xc9, 0x52, 0xc9, 0x74,
	0x73, 0xe1, 0x2d, 0x4f, 0x92, 0xc3, 0xe5, 0x23, 0x96, 0x1c, 0x87, 0x11, 0xaa, 0x86, 0xf4, 0xee,
	0x0c, 0xdd, 0xae, 0x57, 0x29, 0xe8, 0x7a, 0x08, 0xdb, 0xd9, 0x43, 0x97, 0x6f, 0x49, 0xee, 0x31,
	0xe5, 0xfc, 0x31, 0xfb, 0x6f, 0xea, 0xb0, 0xd9, 0x43, 0x76, 0x8a, 0xcc, 0xd0, 0xe2, 0xe4, 0x19,
	0x5c, 0xcc, 0xbc, 0xe0, 0x11, 0x9a, 0x3d, 0xa5, 0xe8, 0xcd, 0xd4, 0xdb, 0x9b, 0x6b, 0x23, 0x1b,
	0xde, 0x0a, 0xb9, 0x0b, 0x55, 0xf5, 0x6a, 0x46, 0xbc, 0xac, 0xb1, 0xfd, 0x2a, 0xe8, 0x35, 0x0a,
	0xd7, 0xb4, 0x83, 0x9f, 0x61, 0x37, 0xf3, 0x0e, 0x22, 0xcc, 0xbd, 0x74, 0x11, 0x16, 0xbd, 0x2d,
	0xb9, 0x08, 0xf3, 0x2f, 0x33, 0x74, 0x85, 0xfc, 0x04, 0xdb, 0x0f, 0x51, 0x74, 0xf0, 0xcc, 0x7e,
	0x5a, 0x1f, 0x65, 0x37, 0x16, 0x56, 0x70, 0xef, 0xff, 0xf3, 0x8d, 0xb4, 0xfb, 0x7b, 0xb0, 0xde,
	0xf3, 0x27, 0xea, 0x13, 0x80, 0x1b, 0x03, 0xfb, 0xdb, 0x81, 0x1b, 0x83, 0xd9, 0x37, 0x03, 0xba,
	0x42, 0x3a, 0x00, 0xb3, 0x19, 0x9e, 0xdc, 0x2a, 0x0a, 0xbb, 0x35, 0x27, 0x79, 0x37, 0xce, 0x37,
	0xd0, 0xfe, 0x9e, 0x4f, 0x47, 0x7a, 0x33, 0x17, 0x17, 0xf0, 0xcd, 0x8f, 0xe8, 0x05, 0x7c, 0x73,
	0xa3, 0xf5, 0x03, 0x58, 0x37, 0x6a, 0x4e, 0xae, 0x17, 0x9a, 0xa7, 0xce, 0xbc, 0x73, 0x56, 0x35,
	0xc2, 0x03, 0x80, 0xd9, 0x68, 0xe6, 0x32, 0xce, 0x4d, 0x86, 0x2e, 0x63, 0x77, 0xaa, 0x7b, 0x01,
	0x9b, 0xd9, 0x0a, 0xe8, 0xf2, 0x2d, 0xec, 0x72, 0x2e, 0xdf, 0x82, 0x1e, 0x46, 0x57, 0xc8, 0x6b,
	0x68, 0x9c, 0xd7, 0x1a, 0xc8, 0xe7, 0xf3, 0x1c, 0xe4, 0xfa, 0x97, 0xf7, 0xd9, 0xa2, 0xe6, 0xfa,
	0xe4, 0xdf, 0xe0, 0x9a, 0x0b, 0x89, 0x5b, 0x14, 0x9b, 0xf3, 0xbc, 0xe5, 0x1b, 0x8e, 0x77, 0x67,
	0x61, 0x7b, 0x7d, 0xfc, 0x0b, 0xd8, 0xcc, 0x96, 0x59, 0x37, 0xa8, 0x85, 0x3d, 0xc2, 0x0d, 0x6a,
	0x41, 0xa5, 0xa6, 0x2b, 0xe4, 0x19, 0x6c, 0xc9, 0x84, 0xb0, 0x6a, 0x21, 0x71, 0xf6, 0x15, 0x14,
	0x67, 0xef, 0xd6, 0x3c, 0x13, 0xed, 0xf8, 0x10, 0x6a, 0x3a, 0x39, 0x9e, 0xaa, 0x91, 0xd7, 0xd9,
	0x91, 0x1b, 0xb2, 0xbd, 0x6b, 0x79, 0x83, 0xe9, 0x18, 0x4d, 0x57, 0xc8, 0x7d, 0xd8, 0x68, 0xf5,
	0xfb, 0x7a, 0x84, 0x25, 0x8e, 0x6d, 0x66, 0x3a, 0xf6, 0xae, 0x16, 0x2f, 0x6a, 0x37, 0x8f, 0xa0,
	0xde, 0xc5, 0x61, 0x72, 0x8a, 0xef, 0xec, 0xa9, 0x0d, 0xb5, 0x87, 0x28, 0xba, 0xe9, 0xa8, 0xea,
	0xd8, 0x5a, 0xe3, 0xb2, 0xf7, 0xbf, 0xa2, 0x25, 0xe5, 0xe4, 0xde, 0x27, 0x70, 0x35, 0x48, 0x86,
	0x4d, 0x7c, 0xed, 0x0f, 0x47, 0x11, 0xf2, 0x8c, 0xe1, 0x8b, 0xcc, 0x17, 0xd0, 0x5f, 0xd6, 0xd4,
	0xcf, 0x57, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xa6, 0x7d, 0xed, 0x34, 0x15, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServerRequestsClient is the client API for ServerRequests service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerRequestsClient interface {
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountReply, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	AccountAuthentication(ctx context.Context, in *AccountAuthenRequest, opts ...grpc.CallOption) (*AccountAuthenReply, error)
	GetNewAccessToken(ctx context.Context, in *GetAccessTokenRequest, opts ...grpc.CallOption) (*GetAccessTokenReply, error)
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostReply, error)
	GetPostPreview(ctx context.Context, in *GetPostPreviewRequest, opts ...grpc.CallOption) (*GetPostPreviewReply, error)
	GetPosts(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostReply, error)
	SearchPost(ctx context.Context, in *SearchPostRequest, opts ...grpc.CallOption) (*SearchPostReply, error)
	ForgetPassword(ctx context.Context, in *ForgetPasswordRequest, opts ...grpc.CallOption) (*ForgetPasswordReply, error)
	ForgetPasswordVerifyCode(ctx context.Context, in *ForgetPasswordVerifyCodeRequest, opts ...grpc.CallOption) (*ForgetPasswordVerifyCodeReply, error)
	ForgetPasswordResetPassword(ctx context.Context, in *ForgetPasswordNewPasswordRequest, opts ...grpc.CallOption) (*ForgetPasswordNewPasswordReply, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordReply, error)
	GetProfileImage(ctx context.Context, in *ProfileImageRequest, opts ...grpc.CallOption) (*ProfileImageReply, error)
	// Query is sent to the server and a list of matching users is returned
	SearchUsers(ctx context.Context, in *UserSearchRequest, opts ...grpc.CallOption) (*UserListReply, error)
	// Unary client request to add a new friend for the user
	AddFriend(ctx context.Context, in *FriendRequest, opts ...grpc.CallOption) (*FriendReply, error)
	// Unary client request to remove an existing friend for the user
	RemoveFriend(ctx context.Context, in *FriendRequest, opts ...grpc.CallOption) (*FriendReply, error)
	GetRoomName(ctx context.Context, in *RoomRequest, opts ...grpc.CallOption) (*RoomReply, error)
}

type serverRequestsClient struct {
	cc *grpc.ClientConn
}

func NewServerRequestsClient(cc *grpc.ClientConn) ServerRequestsClient {
	return &serverRequestsClient{cc}
}

func (c *serverRequestsClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountReply, error) {
	out := new(CreateAccountReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) AccountAuthentication(ctx context.Context, in *AccountAuthenRequest, opts ...grpc.CallOption) (*AccountAuthenReply, error) {
	out := new(AccountAuthenReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/AccountAuthentication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) GetNewAccessToken(ctx context.Context, in *GetAccessTokenRequest, opts ...grpc.CallOption) (*GetAccessTokenReply, error) {
	out := new(GetAccessTokenReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/GetNewAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostReply, error) {
	out := new(CreatePostReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) GetPostPreview(ctx context.Context, in *GetPostPreviewRequest, opts ...grpc.CallOption) (*GetPostPreviewReply, error) {
	out := new(GetPostPreviewReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/GetPostPreview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) GetPosts(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostReply, error) {
	out := new(GetPostReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/GetPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) SearchPost(ctx context.Context, in *SearchPostRequest, opts ...grpc.CallOption) (*SearchPostReply, error) {
	out := new(SearchPostReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/SearchPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) ForgetPassword(ctx context.Context, in *ForgetPasswordRequest, opts ...grpc.CallOption) (*ForgetPasswordReply, error) {
	out := new(ForgetPasswordReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/ForgetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) ForgetPasswordVerifyCode(ctx context.Context, in *ForgetPasswordVerifyCodeRequest, opts ...grpc.CallOption) (*ForgetPasswordVerifyCodeReply, error) {
	out := new(ForgetPasswordVerifyCodeReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/ForgetPasswordVerifyCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) ForgetPasswordResetPassword(ctx context.Context, in *ForgetPasswordNewPasswordRequest, opts ...grpc.CallOption) (*ForgetPasswordNewPasswordReply, error) {
	out := new(ForgetPasswordNewPasswordReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/ForgetPasswordResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordReply, error) {
	out := new(ChangePasswordReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) GetProfileImage(ctx context.Context, in *ProfileImageRequest, opts ...grpc.CallOption) (*ProfileImageReply, error) {
	out := new(ProfileImageReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/GetProfileImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) SearchUsers(ctx context.Context, in *UserSearchRequest, opts ...grpc.CallOption) (*UserListReply, error) {
	out := new(UserListReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/SearchUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) AddFriend(ctx context.Context, in *FriendRequest, opts ...grpc.CallOption) (*FriendReply, error) {
	out := new(FriendReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/AddFriend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) RemoveFriend(ctx context.Context, in *FriendRequest, opts ...grpc.CallOption) (*FriendReply, error) {
	out := new(FriendReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/RemoveFriend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) GetRoomName(ctx context.Context, in *RoomRequest, opts ...grpc.CallOption) (*RoomReply, error) {
	out := new(RoomReply)
	err := c.cc.Invoke(ctx, "/naturaeproto.ServerRequests/GetRoomName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerRequestsServer is the server API for ServerRequests service.
type ServerRequestsServer interface {
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountReply, error)
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	AccountAuthentication(context.Context, *AccountAuthenRequest) (*AccountAuthenReply, error)
	GetNewAccessToken(context.Context, *GetAccessTokenRequest) (*GetAccessTokenReply, error)
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	CreatePost(context.Context, *CreatePostRequest) (*CreatePostReply, error)
	GetPostPreview(context.Context, *GetPostPreviewRequest) (*GetPostPreviewReply, error)
	GetPosts(context.Context, *GetPostRequest) (*GetPostReply, error)
	SearchPost(context.Context, *SearchPostRequest) (*SearchPostReply, error)
	ForgetPassword(context.Context, *ForgetPasswordRequest) (*ForgetPasswordReply, error)
	ForgetPasswordVerifyCode(context.Context, *ForgetPasswordVerifyCodeRequest) (*ForgetPasswordVerifyCodeReply, error)
	ForgetPasswordResetPassword(context.Context, *ForgetPasswordNewPasswordRequest) (*ForgetPasswordNewPasswordReply, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordReply, error)
	GetProfileImage(context.Context, *ProfileImageRequest) (*ProfileImageReply, error)
	// Query is sent to the server and a list of matching users is returned
	SearchUsers(context.Context, *UserSearchRequest) (*UserListReply, error)
	// Unary client request to add a new friend for the user
	AddFriend(context.Context, *FriendRequest) (*FriendReply, error)
	// Unary client request to remove an existing friend for the user
	RemoveFriend(context.Context, *FriendRequest) (*FriendReply, error)
	GetRoomName(context.Context, *RoomRequest) (*RoomReply, error)
}

func RegisterServerRequestsServer(s *grpc.Server, srv ServerRequestsServer) {
	s.RegisterService(&_ServerRequests_serviceDesc, srv)
}

func _ServerRequests_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_AccountAuthentication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountAuthenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).AccountAuthentication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/AccountAuthentication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).AccountAuthentication(ctx, req.(*AccountAuthenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_GetNewAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).GetNewAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/GetNewAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).GetNewAccessToken(ctx, req.(*GetAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_GetPostPreview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostPreviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).GetPostPreview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/GetPostPreview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).GetPostPreview(ctx, req.(*GetPostPreviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_GetPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).GetPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/GetPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).GetPosts(ctx, req.(*GetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_SearchPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).SearchPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/SearchPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).SearchPost(ctx, req.(*SearchPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_ForgetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).ForgetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/ForgetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).ForgetPassword(ctx, req.(*ForgetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_ForgetPasswordVerifyCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgetPasswordVerifyCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).ForgetPasswordVerifyCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/ForgetPasswordVerifyCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).ForgetPasswordVerifyCode(ctx, req.(*ForgetPasswordVerifyCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_ForgetPasswordResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgetPasswordNewPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).ForgetPasswordResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/ForgetPasswordResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).ForgetPasswordResetPassword(ctx, req.(*ForgetPasswordNewPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_GetProfileImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).GetProfileImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/GetProfileImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).GetProfileImage(ctx, req.(*ProfileImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_SearchUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).SearchUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/SearchUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).SearchUsers(ctx, req.(*UserSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_AddFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).AddFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/AddFriend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).AddFriend(ctx, req.(*FriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_RemoveFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).RemoveFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/RemoveFriend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).RemoveFriend(ctx, req.(*FriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_GetRoomName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).GetRoomName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naturaeproto.ServerRequests/GetRoomName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).GetRoomName(ctx, req.(*RoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServerRequests_serviceDesc = grpc.ServiceDesc{
	ServiceName: "naturaeproto.ServerRequests",
	HandlerType: (*ServerRequestsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _ServerRequests_CreateAccount_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _ServerRequests_Login_Handler,
		},
		{
			MethodName: "AccountAuthentication",
			Handler:    _ServerRequests_AccountAuthentication_Handler,
		},
		{
			MethodName: "GetNewAccessToken",
			Handler:    _ServerRequests_GetNewAccessToken_Handler,
		},
		{
			MethodName: "SayHello",
			Handler:    _ServerRequests_SayHello_Handler,
		},
		{
			MethodName: "CreatePost",
			Handler:    _ServerRequests_CreatePost_Handler,
		},
		{
			MethodName: "GetPostPreview",
			Handler:    _ServerRequests_GetPostPreview_Handler,
		},
		{
			MethodName: "GetPosts",
			Handler:    _ServerRequests_GetPosts_Handler,
		},
		{
			MethodName: "SearchPost",
			Handler:    _ServerRequests_SearchPost_Handler,
		},
		{
			MethodName: "ForgetPassword",
			Handler:    _ServerRequests_ForgetPassword_Handler,
		},
		{
			MethodName: "ForgetPasswordVerifyCode",
			Handler:    _ServerRequests_ForgetPasswordVerifyCode_Handler,
		},
		{
			MethodName: "ForgetPasswordResetPassword",
			Handler:    _ServerRequests_ForgetPasswordResetPassword_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _ServerRequests_ChangePassword_Handler,
		},
		{
			MethodName: "GetProfileImage",
			Handler:    _ServerRequests_GetProfileImage_Handler,
		},
		{
			MethodName: "SearchUsers",
			Handler:    _ServerRequests_SearchUsers_Handler,
		},
		{
			MethodName: "AddFriend",
			Handler:    _ServerRequests_AddFriend_Handler,
		},
		{
			MethodName: "RemoveFriend",
			Handler:    _ServerRequests_RemoveFriend_Handler,
		},
		{
			MethodName: "GetRoomName",
			Handler:    _ServerRequests_GetRoomName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "naturaeproto/Naturae.proto",
}
