// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/Naturae.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_caeed9bdc999139e, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_caeed9bdc999139e, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CreateAccountRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=appKey,proto3" json:"appKey,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	FirstName            string   `protobuf:"bytes,4,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,5,opt,name=lastName,proto3" json:"lastName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_caeed9bdc999139e, []int{2}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *CreateAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateAccountRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateAccountRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type CreateAccountReply struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	ErrorList            []string `protobuf:"bytes,3,rep,name=errorList,proto3" json:"errorList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountReply) Reset()         { *m = CreateAccountReply{} }
func (m *CreateAccountReply) String() string { return proto.CompactTextString(m) }
func (*CreateAccountReply) ProtoMessage()    {}
func (*CreateAccountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_caeed9bdc999139e, []int{3}
}

func (m *CreateAccountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountReply.Unmarshal(m, b)
}
func (m *CreateAccountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountReply.Marshal(b, m, deterministic)
}
func (m *CreateAccountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountReply.Merge(m, src)
}
func (m *CreateAccountReply) XXX_Size() int {
	return xxx_messageInfo_CreateAccountReply.Size(m)
}
func (m *CreateAccountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountReply proto.InternalMessageInfo

func (m *CreateAccountReply) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *CreateAccountReply) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *CreateAccountReply) GetErrorList() []string {
	if m != nil {
		return m.ErrorList
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "proto.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "proto.HelloReply")
	proto.RegisterType((*CreateAccountRequest)(nil), "proto.CreateAccountRequest")
	proto.RegisterType((*CreateAccountReply)(nil), "proto.CreateAccountReply")
}

func init() { proto.RegisterFile("proto/Naturae.proto", fileDescriptor_caeed9bdc999139e) }

var fileDescriptor_caeed9bdc999139e = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xcd, 0x4e, 0x02, 0x31,
	0x10, 0x76, 0xe5, 0x47, 0x18, 0xd1, 0xc4, 0x81, 0x98, 0x15, 0x3d, 0x90, 0x1e, 0x8c, 0x27, 0x4c,
	0xd4, 0x17, 0x30, 0x5e, 0x34, 0x1a, 0x0e, 0xe0, 0x0b, 0xd4, 0x75, 0x50, 0x62, 0xd9, 0xd6, 0x69,
	0x57, 0xdd, 0xc7, 0xf0, 0xea, 0xd3, 0x9a, 0xed, 0x76, 0x91, 0x35, 0x9c, 0xda, 0xef, 0xaf, 0xf9,
	0x3a, 0x03, 0x7d, 0xc3, 0xda, 0xe9, 0xf3, 0x89, 0x74, 0x19, 0x4b, 0x1a, 0x7b, 0x84, 0x2d, 0x7f,
	0x08, 0x01, 0xbd, 0x5b, 0x52, 0x4a, 0x4f, 0xe9, 0x3d, 0x23, 0xeb, 0x10, 0xa1, 0x99, 0xca, 0x25,
	0xc5, 0xd1, 0x28, 0x3a, 0xeb, 0x4e, 0xfd, 0x5d, 0x9c, 0x02, 0x04, 0x8f, 0x51, 0x39, 0xc6, 0xb0,
	0xb3, 0x24, 0x6b, 0xe5, 0x4b, 0x65, 0xaa, 0xa0, 0xf8, 0x89, 0x60, 0x70, 0xc3, 0x24, 0x1d, 0x5d,
	0x27, 0x89, 0xce, 0x52, 0x57, 0x3d, 0x7a, 0x08, 0x6d, 0x69, 0xcc, 0x3d, 0xe5, 0x21, 0x11, 0x10,
	0x0e, 0xa0, 0x45, 0x4b, 0xb9, 0x50, 0xf1, 0xb6, 0xa7, 0x4b, 0x80, 0x43, 0xe8, 0x18, 0x69, 0xed,
	0xa7, 0xe6, 0xe7, 0xb8, 0xe1, 0x85, 0x15, 0xc6, 0x13, 0xe8, 0xce, 0x17, 0x6c, 0xdd, 0xa4, 0xe8,
	0xd8, 0xf4, 0xe2, 0x1f, 0x51, 0x24, 0x95, 0x0c, 0x62, 0xab, 0x4c, 0x56, 0x58, 0x7c, 0x01, 0xfe,
	0xeb, 0x56, 0x7c, 0x66, 0x04, 0xbb, 0x32, 0x49, 0xc8, 0xda, 0x47, 0xfd, 0x46, 0x69, 0xa8, 0xb7,
	0x4e, 0xa1, 0x80, 0x1e, 0xd3, 0x9c, 0xc9, 0xbe, 0x96, 0x96, 0xb2, 0x6a, 0x8d, 0x2b, 0x5a, 0x11,
	0xb3, 0xe6, 0x87, 0x85, 0x75, 0x71, 0x63, 0xd4, 0x28, 0x5a, 0xad, 0x88, 0x8b, 0xef, 0x08, 0xf6,
	0x67, 0xc4, 0x1f, 0xc4, 0x61, 0x1e, 0x16, 0xef, 0x60, 0xaf, 0x56, 0x06, 0x8f, 0xcb, 0xad, 0x8c,
	0x37, 0x8d, 0x6f, 0x78, 0xb4, 0x59, 0x34, 0x2a, 0x17, 0x5b, 0x78, 0x05, 0x9d, 0x99, 0xcc, 0xfd,
	0x7e, 0xb0, 0x1f, 0x8c, 0xeb, 0x1b, 0x1d, 0x1e, 0xd4, 0x49, 0x9f, 0x7a, 0x6a, 0x7b, 0xee, 0xf2,
	0x37, 0x00, 0x00, 0xff, 0xff, 0x74, 0xd1, 0xf0, 0x21, 0x1b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServerRequestsClient is the client API for ServerRequests service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerRequestsClient interface {
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountReply, error)
	//    rpc Login (LoginRequest) returns(LoginReply){}
	//    rpc AccountAuthentication(AccountAuthenRequest) returns(AccountAuthenReply){}
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type serverRequestsClient struct {
	cc *grpc.ClientConn
}

func NewServerRequestsClient(cc *grpc.ClientConn) ServerRequestsClient {
	return &serverRequestsClient{cc}
}

func (c *serverRequestsClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountReply, error) {
	out := new(CreateAccountReply)
	err := c.cc.Invoke(ctx, "/proto.ServerRequests/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverRequestsClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/proto.ServerRequests/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerRequestsServer is the server API for ServerRequests service.
type ServerRequestsServer interface {
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountReply, error)
	//    rpc Login (LoginRequest) returns(LoginReply){}
	//    rpc AccountAuthentication(AccountAuthenRequest) returns(AccountAuthenReply){}
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterServerRequestsServer(s *grpc.Server, srv ServerRequestsServer) {
	s.RegisterService(&_ServerRequests_serviceDesc, srv)
}

func _ServerRequests_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ServerRequests/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerRequests_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRequestsServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ServerRequests/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRequestsServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServerRequests_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ServerRequests",
	HandlerType: (*ServerRequestsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _ServerRequests_CreateAccount_Handler,
		},
		{
			MethodName: "SayHello",
			Handler:    _ServerRequests_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/Naturae.proto",
}
